/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AnTouPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE = "an-tou-desk";
var DEFAULT_TITLE = "\u683C\u7269\u6210\u6816";
var RECENT_CAP = 3;
var DEFAULT_SETTINGS = {
  title: DEFAULT_TITLE,
  openOnStart: true,
  collapseExplorer: true,
  applyLook: true,
  applySerif: true,
  hideRibbon: false,
  skipPaths: ["attachments"],
  skipSeeded: false,
  rooms: [],
  uiLang: "zh",
  welcomed: false
};
var COPY = {
  zh: {
    language: "\u754C\u9762\u8BED\u8A00",
    languageDesc: "\u53EA\u6539\u8BBE\u7F6E\u9875\u7684\u8BF4\u660E\u3002\u4E66\u684C\u5361\u7247\u4E0A\u7684\u4E2D\u6587\u6807\u9898\u8FD8\u662F\u4F60\u81EA\u5DF1\u586B\u7684\u3002",
    chinese: "\u4E2D\u6587",
    english: "English",
    desk: "\u4E66\u684C",
    title: "\u4E66\u684C\u6807\u9898",
    titleDesc: "\u9996\u9875\u6700\u5927\u90A3\u884C\u5B57\uFF0C\u4E5F\u663E\u793A\u5728\u6807\u7B7E\u4E0A\u3002",
    look: "\u8584\u8377\u7EFF\u914D\u8272",
    lookDesc: "\u8584\u8377\u7EFF\u5E95\u8272\u3001\u6E10\u53D8\u80CC\u666F\uFF0C\u72B6\u6001\u680F\u548C\u6807\u7B7E\u680F\u53D8\u900F\u660E\u3002\u5173\u6389\u5C31\u53EA\u7559\u5361\u7247\u4E66\u684C\uFF0C\u989C\u8272\u4ECD\u7528\u4F60\u73B0\u5728\u7684\u4E3B\u9898\u3002",
    serif: "\u886C\u7EBF\u5B57\u4F53",
    serifDesc: "\u6B63\u6587\u548C\u6807\u9898\u6362\u6210\u886C\u7EBF\u5B57\uFF0C\u884C\u9AD8\u653E\u5BBD\u3002\u5173\u6389\u5C31\u7528\u4F60\u4E3B\u9898\u539F\u672C\u7684\u5B57\u4F53\u3002",
    hideRibbon: "\u9690\u85CF\u5DE6\u8FB9\u7684\u56FE\u6807\u680F",
    hideRibbonDesc: "\u66F4\u6E05\u723D\uFF0C\u4F46\u5207\u6362\u5E93\u548C\u8BBE\u7F6E\u7684\u5165\u53E3\u4E5F\u4F1A\u8DDF\u7740\u4E0D\u89C1\u3002",
    openOnStart: "\u6253\u5F00\u5E93\u65F6\u8FDB\u5165\u4E66\u684C",
    openOnStartDesc: "\u542F\u52A8\u65F6\u6253\u5F00\u4E66\u684C\uFF0C\u800C\u4E0D\u662F\u4E0A\u6B21\u90A3\u7BC7\u7B14\u8BB0\u3002",
    collapse: "\u6536\u8D77\u6587\u4EF6\u5217\u8868",
    collapseDesc: "\u6253\u5F00\u4E66\u684C\u65F6\u628A\u5DE6\u8FB9\u6587\u4EF6\u6811\u6536\u8D77\u6765\u3002",
    skip: "\u8DF3\u8FC7\u8FD9\u4E9B\u8DEF\u5F84",
    skipDesc: "\u7528\u9017\u53F7\u5206\u9694\u3002\u8FD9\u4E9B\u6587\u4EF6\u5939\u4E0D\u4F1A\u51FA\u73B0\u5728\u5361\u7247\u548C\u300C\u6700\u8FD1\u300D\u91CC\u3002",
    rooms: "\u623F\u95F4",
    roomsDesc: "\u4E0B\u9762\u8FD9\u5F20\u56FE\u5C31\u662F\u4E66\u684C\u5361\u7247\uFF0C\u5BF9\u7167\u7740\u586B\u5C31\u884C\u3002",
    addRoom: "\u6DFB\u52A0\u623F\u95F4",
    fromVault: "\u6309\u5E93\u6839\u76EE\u5F55\u751F\u6210",
    fromVaultNotice: "\u5DF2\u6309\u6587\u4EF6\u5939\u66F4\u65B0\u623F\u95F4\u3002\u5DF2\u6709\u540D\u79F0\u3001\u8BF4\u660E\u548C\u5F00\u5173\u6CA1\u52A8\u3002",
    roomId: "\u7F16\u53F7",
    remove: "\u5220\u9664\u8FD9\u4E2A\u623F\u95F4",
    name: "\u540D\u79F0",
    nameDesc: "\u5361\u7247\u6B63\u4E2D\u95F4\u6700\u5927\u7684\u90A3\u884C\u5B57\u3002",
    folder: "\u6587\u4EF6\u5939",
    folderDesc: "\u5E93\u91CC\u7684\u8DEF\u5F84\uFF0C\u6BD4\u5982 00-Inbox\u3002\u6536\u7EB3\u67DC\u8FD9\u79CD\u5206\u7EC4\u8BF7\u7559\u7A7A\u3002",
    folderMissing: "\u5E93\u91CC\u6CA1\u6709\u8FD9\u4E2A\u6587\u4EF6\u5939\u3002",
    folderDidYouMean: "\u4F60\u662F\u4E0D\u662F\u60F3\u586B {folder}\uFF1F",
    kicker: "\u5DE6\u4E0A\u89D2\u5C0F\u5B57",
    kickerDesc: "\u5361\u7247\u5DE6\u4E0A\u89D2\u90A3\u4E00\u884C\uFF0C\u6BD4\u5982 Inbox\u3002",
    line: "\u5E95\u4E0B\u90A3\u884C\u8BF4\u660E",
    lineDesc: "\u6807\u9898\u4E0B\u9762\u90A3\u53E5\uFF0C\u5199\u8FD9\u683C\u662F\u5E72\u4EC0\u4E48\u7684\u3002",
    parent: "\u653E\u8FDB\u54EA\u4E2A\u623F\u95F4",
    parentDesc: "\u9009\u300C\u4E0D\u653E\uFF0C\u7559\u5728\u9996\u9875\u300D\u5B83\u5C31\u7559\u5728\u9996\u9875\uFF1B\u9009\u53E6\u4E00\u4E2A\u623F\u95F4\uFF0C\u5B83\u5C31\u6536\u8FDB\u90A3\u5F20\u5361\u91CC\u3002",
    parentNone: "\u4E0D\u653E\uFF0C\u7559\u5728\u9996\u9875",
    parentMissing: "\u26A0\uFE0F {id}\uFF08\u4E0D\u5B58\u5728\uFF09",
    parentUnselectable: "\u26A0\uFE0F {name}\uFF08\u5F53\u524D\u503C\uFF0C\u4E0D\u80FD\u518D\u9009\uFF09",
    quiet: "\u5361\u7247\u53D8\u6DE1",
    quietDesc: "\u6253\u5F00\u540E\u8FD9\u5F20\u5361\u53D8\u6DE1\uFF0C\u91CC\u9762\u7684\u7B14\u8BB0\u4E5F\u4E0D\u8FDB\u300C\u6700\u8FD1\u300D\u3002",
    pinBacklog: "\u8FDB\u623F\u95F4\u5148\u770B BACKLOG",
    pinBacklogDesc: "\u6CA1\u6709 BACKLOG.md \u65F6\u4E5F\u53EF\u4EE5\u5F3A\u5236\uFF1A\u5176\u5B83\u7B14\u8BB0\u53EA\u7559\u51E0\u5F20\u6700\u8FD1\u7684\u3002",
    backlogNote: "\u8FD9\u4E2A\u623F\u95F4\u6709 BACKLOG.md",
    backlogNoteDesc: "\u8FDB\u623F\u95F4\u4F1A\u5148\u770B\u5230\u5B83\uFF0C\u5176\u5B83\u7B14\u8BB0\u53D8\u6210\u4E0B\u9762\u51E0\u5F20\u6700\u8FD1\u7684\u3002\u653E\u8FDB BACKLOG.md \u5C31\u4F1A\u8FD9\u6837\uFF0C\u4E0D\u7528\u53E6\u5F00\u5F00\u5173\u3002",
    maxNotes: "\u6700\u591A\u663E\u793A\u51E0\u5F20",
    maxNotesDesc: "\u8FD9\u4E2A\u623F\u95F4\u91CC\u6700\u591A\u663E\u793A\u591A\u5C11\u5F20\u7B14\u8BB0\u5361\u7247\u3002\u7559\u7A7A\u5C31\u81EA\u52A8\u51B3\u5B9A\u3002",
    newRoom: "\u65B0\u623F\u95F4",
    saveRoom: "\u4FDD\u5B58",
    draftHint: "\u672A\u4FDD\u5B58\u3002\u586B\u597D\u540E\u70B9\u4FDD\u5B58\uFF0C\u8FD9\u5F20\u5361\u4F1A\u79FB\u5230\u6700\u4E0B\u9762\u3002",
    deleteTitle: "\u5220\u6389\u300C{name}\u300D\uFF1F",
    deleteHolds: "\u91CC\u9762\u8FD8\u6536\u7740 {n} \u4E2A\u623F\u95F4\u3002\u5220\u6389\u4E4B\u540E\u5B83\u4EEC\u4F1A\u56DE\u5230\u9996\u9875\uFF0C\u5B83\u4EEC\u81EA\u5DF1\u7684\u5B50\u623F\u95F4\u8DDF\u7740\u4E00\u8D77\u8D70\u3002",
    deleteNotesSafe: "\u4F60\u7684\u7B14\u8BB0\u548C\u6587\u4EF6\u5939\u4E00\u4E2A\u90FD\u4E0D\u4F1A\u52A8\u3002",
    deleteConfirm: "\u5220\u6389",
    deleteCancel: "\u7B97\u4E86",
    roleGroup: "\u9996\u9875\u5206\u7EC4 \xB7 {n} \u4E2A\u5B50\u623F\u95F4",
    roleHome: "\u9996\u9875 \xB7 {folder}",
    roleNested: "\u6536\u5728\u300C{name}\u300D\u91CC",
    roleParentMissing: "\u7236\u623F\u95F4\u4E0D\u5B58\u5728\uFF0C\u8FD9\u5F20\u5361\u4E0D\u4F1A\u663E\u793A",
    helpTitle: "\u4E66\u684C\u5361\u7247\u957F\u8FD9\u6837",
    helpKickerCap: "\u5DE6\u4E0A\u89D2\u5C0F\u5B57",
    helpNameCap: "\u540D\u79F0",
    helpLineCap: "\u5E95\u4E0B\u90A3\u884C\u8BF4\u660E",
    helpFolderCap: "\u6587\u4EF6\u5939",
    helpFolderNote: "\u586B 00-Inbox \u8FD9\u7C7B\u8DEF\u5F84\u3002\u7559\u7A7A\u7684\u8BDD\uFF0C\u70B9\u8FDB\u53BB\u770B\u5230\u7684\u662F\u5B50\u623F\u95F4\uFF0C\u4E0D\u662F\u7B14\u8BB0\u3002",
    helpParentCap: "\u653E\u8FDB\u54EA\u4E2A\u623F\u95F4",
    helpParentNote: "\u5728\u300C\u653E\u8FDB\u54EA\u4E2A\u623F\u95F4\u300D\u91CC\u9009\u300C\u6536\u7EB3\u67DC\u300D\uFF0C\u8FD9\u5F20\u5361\u5C31\u4ECE\u9996\u9875\u6536\u8FDB\u67DC\u5B50\u91CC\u3002",
    helpQuietCap: "\u5361\u7247\u53D8\u6DE1",
    helpQuietNote: "\u6253\u5F00\u540E\u8FD9\u5F20\u5361\u53D8\u6DE1\uFF0C\u91CC\u9762\u7684\u7B14\u8BB0\u4E5F\u4E0D\u51FA\u73B0\u5728\u300C\u6700\u8FD1\u300D\u3002",
    helpCountCap: "\u6570\u91CF\uFF0C\u4E0D\u7528\u586B",
    helpHome: "\u9996\u9875",
    helpInside: "\u70B9\u8FDB\u6536\u7EB3\u67DC\u4E4B\u540E",
    sampleName: "\u5165\u53E3",
    sampleLine: "\u4ECA\u5929\u8FD9\u4E00\u5F20",
    sampleCabinet: "\u6536\u7EB3\u67DC",
    sampleThinking: "\u4E2A\u4EBA\u601D\u8003",
    staleFolder: "\u6587\u4EF6\u5939\u5DF2\u4E0D\u5B58\u5728",
    roleGroupHidden: "\uFF08\u6587\u4EF6\u5939 {folder} \u91CC\u7684\u7B14\u8BB0\u4E0D\u4F1A\u663E\u793A\uFF09",
    roleNoFolder: "\u8FD8\u6CA1\u914D\u6587\u4EF6\u5939\uFF0C\u70B9\u4E86\u6CA1\u53CD\u5E94",
    maxNotesBad: "\u53EA\u80FD\u586B\u5927\u4E8E 0 \u7684\u6574\u6570\uFF0C\u7559\u7A7A\u5C31\u81EA\u52A8\u51B3\u5B9A\u3002",
    nameRequired: "\u5148\u7ED9\u8FD9\u4E2A\u623F\u95F4\u8D77\u4E2A\u540D\u5B57\u3002",
    recent: "\u6700\u8FD1",
    emptyRooms: "\u8FD8\u6CA1\u6709\u623F\u95F4\u3002\u6253\u5F00\u8BBE\u7F6E\u6DFB\u52A0\u6587\u4EF6\u5939\uFF0C\u6216\u4ECE\u5E93\u6839\u76EE\u5F55\u751F\u6210\u3002",
    backlogLede: "\u6B63\u672C\u5728 Backlog\u3002",
    mainFile: "\u6B63\u672C",
    recentSlips: "\u6700\u8FD1\u7684\u7EB8\u6761",
    noMoreNotes: "\u6CA1\u6709\u66F4\u591A\u7B14\u8BB0\u3002",
    emptyFolder: "\u8FD9\u4E00\u683C\u8FD8\u6CA1\u6709\u7B14\u8BB0\u3002",
    newNote: "\u65B0\u7B14\u8BB0",
    newNotePlaceholder: "\u8FD9\u7BC7\u53EB\u4EC0\u4E48",
    createFailed: "\u6CA1\u5199\u6210\u3002",
    folderGone: "\u6587\u4EF6\u5939\u4E0D\u5728\u3002",
    untitled: "\u672A\u547D\u540D",
    addHere: "\u5728\u8FD9\u91CC\u65B0\u5EFA\u7B14\u8BB0",
    more: (n) => "\u5176\u4F59 " + n + " \u6761",
    noteCount: (n) => n + " \u7BC7\u7B14\u8BB0",
    welcomeTitle: "\u4E66\u684C\u51C6\u5907\u597D\u4E86",
    welcomeSub: "\u5728\u52A8\u4F60\u7684\u5E93\u4E4B\u524D\uFF0C\u5148\u8BF4\u6E05\u695A\u6211\u505A\u4E86\u4EC0\u4E48\u3002",
    welcomePoint1: "\u6362\u4E0A\u4E86\u8584\u8377\u7EFF\u914D\u8272\u548C\u886C\u7EBF\u5B57\uFF0C\u968F\u65F6\u53EF\u4EE5\u5728\u8BBE\u7F6E\u91CC\u5173\u6389",
    welcomePoint2: "\u628A\u5DE6\u8FB9\u7684\u6587\u4EF6\u6811\u6536\u8D77\u6765\u4E86\uFF0C\u70B9\u4E00\u4E0B\u5C31\u80FD\u62C9\u56DE\u6765",
    welcomePoint3: "\u6CA1\u6709\u9690\u85CF\u5DE6\u8FB9\u90A3\u6392\u56FE\u6807\uFF0C\u60F3\u66F4\u6E05\u723D\u53EF\u4EE5\u81EA\u5DF1\u53BB\u5F00",
    welcomePoint4: "\u4F60\u7684\u7B14\u8BB0\u548C\u6587\u4EF6\u5939\u4E00\u4E2A\u90FD\u6CA1\u52A8\u8FC7",
    welcomePick: (n) => "\u4F60\u7684\u5E93\u91CC\u6709 " + n + " \u4E2A\u6587\u4EF6\u5939\u3002\u6311\u51E0\u4E2A\u653E\u9996\u9875\uFF1A",
    welcomeAddAll: "\u5168\u90FD\u653E\u4E0A\u53BB",
    welcomeStart: "\u5C31\u7528\u9009\u4E2D\u7684\u8FD9\u51E0\u4E2A\uFF0C\u5F00\u59CB"
  },
  en: {
    language: "Language",
    languageDesc: "Settings copy only. Card titles stay whatever you typed.",
    chinese: "\u4E2D\u6587",
    english: "English",
    desk: "Desk",
    title: "Desk title",
    titleDesc: "The large heading on the home cards and the tab.",
    look: "Mint palette",
    lookDesc: "Mint paper, soft gradients, transparent status and tab bars. Off keeps the cards and your current theme.",
    serif: "Serif type",
    serifDesc: "Serif body and headings with looser line height. Off uses your theme's own fonts.",
    hideRibbon: "Hide the ribbon",
    hideRibbonDesc: "Tidier, but the vault switcher and settings entry go with it.",
    openOnStart: "Open on start",
    openOnStartDesc: "Show the desk when the vault opens, instead of the last note.",
    collapse: "Collapse file explorer",
    collapseDesc: "Fold the left file tree when the desk opens.",
    skip: "Skip these paths",
    skipDesc: "Comma-separated folder prefixes hidden from cards and recents.",
    rooms: "Rooms",
    roomsDesc: "The picture below is a desk card. Fill the fields to match.",
    addRoom: "Add room",
    fromVault: "Build from top-level folders",
    fromVaultNotice: "Rooms updated from folders. Names, captions, and toggles were kept.",
    roomId: "Id",
    remove: "Remove this room",
    name: "Name",
    nameDesc: "The large title in the middle of the card.",
    folder: "Folder",
    folderDesc: "A vault path such as 00-Inbox. Leave empty for a group like Cabinet.",
    folderMissing: "No such folder in the vault.",
    folderDidYouMean: "Did you mean {folder}?",
    kicker: "Top-left text",
    kickerDesc: "The small line at the top-left, such as Inbox.",
    line: "Caption under the title",
    lineDesc: "The sentence under the title, what this room is for.",
    parent: "Put inside this room",
    parentDesc: 'Pick "Leave on home" to keep it on the home grid, or pick the room it should live inside.',
    parentNone: "Leave on home",
    parentMissing: "\u26A0\uFE0F {id} (missing)",
    parentUnselectable: "\u26A0\uFE0F {name} (current, not selectable)",
    quiet: "Fade the card",
    quietDesc: "The card fades, and its notes stay out of recents.",
    pinBacklog: "Show BACKLOG first",
    pinBacklogDesc: "Force the same layout without a BACKLOG.md: other notes stay as a few recent slips.",
    backlogNote: "This room has BACKLOG.md",
    backlogNoteDesc: "Opening the room shows it first; other notes become a few recent slips. Automatic when that file exists.",
    maxNotes: "Max notes shown",
    maxNotesDesc: "How many note cards this room shows at most. Empty means automatic.",
    newRoom: "New room",
    saveRoom: "Save",
    draftHint: "Unsaved. Fill it in, then save, and it moves to the bottom.",
    deleteTitle: 'Delete "{name}"?',
    deleteHolds: "It holds {n} rooms. They move back to home, and their own children come with them.",
    deleteNotesSafe: "Your notes and folders are untouched.",
    deleteConfirm: "Delete",
    deleteCancel: "Cancel",
    roleGroup: "Home group \xB7 {n} children",
    roleHome: "Home \xB7 {folder}",
    roleNested: 'Inside "{name}"',
    roleParentMissing: "Parent missing \u2014 this card is hidden",
    helpTitle: "A desk card looks like this",
    helpKickerCap: "Top-left text",
    helpNameCap: "Name",
    helpLineCap: "Caption under the title",
    helpFolderCap: "Folder",
    helpFolderNote: "A path like 00-Inbox. Leave empty and this card is only a group.",
    helpParentCap: "Put inside this room",
    helpParentNote: 'Pick "Cabinet" under "Put inside this room" and the card leaves the home grid.',
    helpQuietCap: "Fade the card",
    helpQuietNote: "The card fades, and its notes stay out of recents.",
    helpCountCap: "Count, automatic",
    helpHome: "Home",
    helpInside: "After you open Cabinet",
    sampleName: "Inbox",
    sampleLine: "Today's one",
    sampleCabinet: "Cabinet",
    sampleThinking: "Thinking",
    staleFolder: "Folder is gone",
    roleGroupHidden: " (notes in {folder} stay hidden)",
    roleNoFolder: "No folder yet \u2014 this card does nothing",
    maxNotesBad: "Whole number above zero, or leave it empty.",
    nameRequired: "Give the room a name first.",
    recent: "Recent",
    emptyRooms: "No rooms yet. Add folders in settings, or build them from your vault.",
    backlogLede: "The main file is Backlog.",
    mainFile: "Main file",
    recentSlips: "Recent slips",
    noMoreNotes: "No more notes.",
    emptyFolder: "No notes in this room yet.",
    newNote: "New note",
    newNotePlaceholder: "What is it called",
    createFailed: "Could not create the note.",
    folderGone: "That folder is gone.",
    untitled: "Untitled",
    addHere: "New note here",
    more: (n) => n + " more",
    noteCount: (n) => n + " notes",
    welcomeTitle: "Your desk is ready",
    welcomeSub: "Before touching your vault, here is what changed.",
    welcomePoint1: "Mint palette and serif type \u2014 switch them off in settings anytime",
    welcomePoint2: "The file tree is folded \u2014 one click brings it back",
    welcomePoint3: "The ribbon is untouched \u2014 hide it yourself if you want",
    welcomePoint4: "Your notes and folders were not touched",
    welcomePick: (n) => "Your vault has " + n + " folders. Pick a few for the home grid:",
    welcomeAddAll: "Add all",
    welcomeStart: "Start with these"
  }
};
function slug(name) {
  const s = name.toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]+/g, "-").replace(/^-|-$/g, "");
  return s || "room-" + Date.now().toString(36);
}
function uniqueId(base, used) {
  const root = base || "room";
  if (!used.has(root)) {
    used.add(root);
    return root;
  }
  let n = 2;
  while (used.has(root + "-" + n))
    n++;
  const id = root + "-" + n;
  used.add(id);
  return id;
}
function kickerOf(folderName) {
  let s = folderName.replace(/^\d+[-_\s]*/, "").trim();
  s = s.replace(/（[^）]*）/g, "").replace(/\([^)]*\)/g, "").trim();
  if (!s)
    s = folderName.replace(/^\d+[-_\s]*/, "").trim() || folderName;
  if (/[\u4e00-\u9fff]/.test(s)) {
    s = s.replace(/^[A-Za-z0-9]+[-_]/, "").trim() || s;
    return s.slice(0, 4);
  }
  if (/^[A-Za-z0-9][A-Za-z0-9._ -]*$/.test(s)) {
    const parts = s.split(/[-_\s]+/).filter(Boolean);
    if (parts.length === 1) {
      const w = parts[0];
      return w.length <= 12 ? w : w.slice(0, 8);
    }
    const first = parts[0];
    if (first.length >= 3 && first.length <= 10)
      return first;
    return parts.map((p) => p[0]).join("").slice(0, 8);
  }
  return s.slice(0, 4);
}
function noteCountLine(n, copy) {
  if (n <= 0)
    return void 0;
  return copy.noteCount(n);
}
function isAutoLine(line) {
  if (!line)
    return false;
  const s = line.trim();
  return /^\d+\s*篇笔记$/.test(s) || /^\d+\s*notes?$/i.test(s);
}
function isAutoKicker(room) {
  if (!room.kicker || !room.folder)
    return false;
  const base = room.folder.slice(room.folder.lastIndexOf("/") + 1);
  return room.kicker === kickerOf(base);
}
function inFolder(file, folder) {
  if (!folder)
    return false;
  return file.path === folder + ".md" || file.path.startsWith(folder + "/");
}
function skipped(path, skipPaths) {
  return skipPaths.some((s) => path === s || path.startsWith(s + "/"));
}
function weakBasename(file) {
  return /^\d{4}-\d{2}-\d{2}\b/.test(file.basename) || /quick$/i.test(file.basename);
}
function titleOf(file) {
  if (weakBasename(file))
    return "";
  if (file.basename === "BACKLOG")
    return "Backlog";
  return file.basename;
}
function frontmatterTitle(app, file) {
  var _a, _b;
  const raw = (_b = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter) == null ? void 0 : _b.title;
  if (typeof raw === "string" && raw.trim())
    return raw.trim();
  if (Array.isArray(raw) && raw.length && String(raw[0]).trim())
    return String(raw[0]).trim();
  return "";
}
function firstH1(app, file, body) {
  var _a, _b, _c;
  const heading = (_b = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.headings) == null ? void 0 : _b.find((h) => h.level === 1);
  if ((_c = heading == null ? void 0 : heading.heading) == null ? void 0 : _c.trim())
    return heading.heading.trim();
  for (const raw of body.split("\n")) {
    const m = raw.trim().match(/^#\s+(.+)$/);
    if (m)
      return m[1].replace(/\s+#+\s*$/, "").trim();
  }
  return "";
}
function firstReadableFrom(body) {
  for (const raw of body.split("\n")) {
    let ln = raw.trim();
    if (!ln)
      continue;
    if (ln === "---" || ln === "***" || ln === "___")
      continue;
    if (ln.startsWith("```") || ln.startsWith("`"))
      continue;
    if (ln.startsWith("#"))
      continue;
    if (ln.startsWith("!"))
      continue;
    if (ln.startsWith(">"))
      continue;
    ln = ln.replace(/^[-*+]\s+\[[ xX]\]\s*/, "").replace(/^[-*+]\s+/, "").replace(/^\d+\.\s+/, "").replace(/\[([^\]]+)\]\([^)]*\)/g, "$1").replace(/\[\[([^\]|]+)(\|[^\]]*)?\]\]/g, (_m, p1, p2) => p2 ? String(p2).slice(1) : p1).replace(/`[^`]+`/g, "").replace(/[*_]/g, "").replace(/\s+/g, " ").trim();
    if (ln.length < 2)
      continue;
    return ln.slice(0, 48);
  }
  return "";
}
function stripFrontmatter(app, file, text) {
  var _a, _b, _c;
  const offset = (_c = (_b = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatterPosition) == null ? void 0 : _b.end) == null ? void 0 : _c.offset;
  if (typeof offset === "number" && offset > 0 && offset <= text.length) {
    return text.slice(offset);
  }
  if (!text.startsWith("---"))
    return text;
  const end = text.indexOf("\n---", 3);
  if (end === -1)
    return text;
  return text.slice(end + 4);
}
async function noteCardCopy(app, file) {
  if (file.basename === "BACKLOG")
    return { title: "Backlog", line: "" };
  let body = "";
  try {
    body = stripFrontmatter(app, file, await app.vault.cachedRead(file));
  } catch (e) {
  }
  const yaml = frontmatterTitle(app, file);
  const h1 = firstH1(app, file, body);
  const sentence = firstReadableFrom(body);
  const base = file.basename;
  const title = yaml || h1 || sentence || (weakBasename(file) ? "" : titleOf(file)) || base;
  const line = sentence && sentence !== title ? sentence : "";
  return { title, line };
}
function todayLabel(uiLang) {
  const tag = uiLang === "en" ? "en-US" : "zh-CN";
  return new Date().toLocaleDateString(tag, { month: "long", day: "numeric" });
}
function twoDigits(n) {
  return (n < 10 ? "0" : "") + String(n);
}
function inboxStamp() {
  const d = new Date();
  return `${d.getFullYear()}-${twoDigits(d.getMonth() + 1)}-${twoDigits(d.getDate())} ${twoDigits(d.getHours())}${twoDigits(d.getMinutes())}`;
}
function safeName(name, copy) {
  return name.replace(/[\\/:*?"<>|]/g, "").replace(/\s+/g, " ").trim() || copy.untitled;
}
function isInboxFolder(folder) {
  return /inbox/i.test(folder);
}
function folderKey(path) {
  return path.toLowerCase().replace(/[\d\-_.\/\s]+/g, "");
}
function closestFolder(query, folders) {
  const q = query.trim();
  if (!q)
    return "";
  const lower = q.toLowerCase();
  for (const f of folders) {
    if (f.toLowerCase() === lower)
      return f;
  }
  const key = folderKey(q);
  if (key) {
    for (const f of folders) {
      if (folderKey(f) === key)
        return f;
    }
  }
  for (const f of folders) {
    const fl = f.toLowerCase();
    if (fl.length < 2)
      continue;
    if (fl.indexOf(lower) !== -1 || lower.indexOf(fl) !== -1)
      return f;
  }
  return "";
}
var NameModal = class extends import_obsidian.Modal {
  constructor(app, preset, t, onSubmit) {
    super(app);
    this.preset = preset || "";
    this.t = t;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    this.titleEl.setText(this.t.newNote);
    const input = this.contentEl.createEl("input", { type: "text", cls: "prompt-input" });
    input.value = this.preset;
    input.placeholder = this.t.newNotePlaceholder;
    input.addEventListener("keydown", (e) => {
      if (e.key !== "Enter")
        return;
      e.preventDefault();
      const v = input.value.trim();
      this.close();
      this.onSubmit(v);
    });
    input.focus();
    if (this.preset)
      input.select();
  }
};
var FolderSuggest = class extends import_obsidian.AbstractInputSuggest {
  constructor(app, inputEl, onPick) {
    super(app, inputEl);
    this.inputEl = inputEl;
    this.onPick = onPick;
    this.limit = 20;
  }
  getSuggestions(query) {
    const all = this.app.vault.getAllFolders(false).map((f) => f.path);
    const q = query.trim().toLowerCase();
    if (!q)
      return all.slice(0, this.limit);
    return all.filter((p) => p.toLowerCase().indexOf(q) !== -1).slice(0, this.limit);
  }
  renderSuggestion(value, el) {
    el.setText(value);
  }
  selectSuggestion(value) {
    this.inputEl.value = value;
    this.onPick(value);
    this.close();
  }
};
var ConfirmModal = class extends import_obsidian.Modal {
  constructor(app, opts) {
    super(app);
    this.heading = opts.title;
    this.lines = opts.lines;
    this.confirmText = opts.confirm;
    this.cancelText = opts.cancel;
    this.onConfirm = opts.onConfirm;
  }
  onOpen() {
    this.titleEl.setText(this.heading);
    for (const line of this.lines) {
      this.contentEl.createEl("p", { cls: "an-tou-confirm-line", text: line });
    }
    const row = this.contentEl.createDiv({ cls: "an-tou-confirm-actions" });
    const cancel = row.createEl("button", {
      text: this.cancelText,
      attr: { type: "button" }
    });
    cancel.addEventListener("click", () => this.close());
    const ok = row.createEl("button", {
      cls: "mod-warning",
      text: this.confirmText,
      attr: { type: "button" }
    });
    ok.addEventListener("click", () => {
      this.close();
      this.onConfirm();
    });
  }
};
var DeskView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.stack = [{ type: "home" }];
    this._tid = 0;
    this.renderSeq = 0;
    this.dirty = false;
    this.renderFiles = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return this.plugin.settings.title || DEFAULT_TITLE;
  }
  getIcon() {
    return "layout-grid";
  }
  copy() {
    return this.plugin.settings.uiLang === "en" ? COPY.en : COPY.zh;
  }
  async onOpen() {
    this.contentEl.addClass("an-tou-view");
    this.registerEvent(this.app.vault.on("create", () => this.safeRender()));
    this.registerEvent(this.app.vault.on("delete", () => this.safeRender()));
    this.registerEvent(this.app.vault.on("rename", () => this.safeRender()));
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (this.modifyAffectsPage(file))
          this.safeRender();
      })
    );
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        if (this.dirty && this.isShownNow()) {
          this.dirty = false;
          void this.render();
        }
      })
    );
    await this.render();
  }
  async onClose() {
    if (this._tid)
      window.clearTimeout(this._tid);
    this.renderSeq++;
    this.contentEl.empty();
  }
  isShownNow() {
    if (typeof this.contentEl.isShown === "function")
      return this.contentEl.isShown();
    return this.contentEl.offsetParent !== null;
  }
  modifyAffectsPage(file) {
    if (!(file instanceof import_obsidian.TFile))
      return true;
    const page = this.current();
    if (page.type === "folder" || page.type === "more") {
      return inFolder(file, page.folder);
    }
    if (page.type === "home") {
      return !!this.ownerOf(file, this.liveFolders());
    }
    return true;
  }
  safeRender() {
    if (this.current().type === "welcome")
      return;
    if (!this.isShownNow()) {
      this.dirty = true;
      if (this._tid) {
        window.clearTimeout(this._tid);
        this._tid = 0;
      }
      return;
    }
    if (this._tid)
      window.clearTimeout(this._tid);
    this._tid = window.setTimeout(() => {
      this._tid = 0;
      void this.render();
    }, 200);
  }
  resetHome() {
    this.stack = [{ type: "home" }];
    return this.render();
  }
  current() {
    return this.stack[this.stack.length - 1];
  }
  push(page) {
    this.stack.push(page);
    void this.render();
  }
  back() {
    if (this.stack.length > 1) {
      this.stack.pop();
      void this.render();
    }
  }
  mdIn(folder, extraSkip = []) {
    var _a;
    if (!folder)
      return [];
    const skip = this.plugin.settings.skipPaths;
    const all = (_a = this.renderFiles) != null ? _a : this.app.vault.getMarkdownFiles();
    return all.filter((f) => {
      if (!inFolder(f, folder))
        return false;
      if (skipped(f.path, skip))
        return false;
      return !extraSkip.some((s) => f.path.endsWith(s) || f.basename === s);
    });
  }
  subfolders(folder) {
    const af = this.app.vault.getAbstractFileByPath(folder);
    if (!(af instanceof import_obsidian.TFolder))
      return [];
    const skip = this.plugin.settings.skipPaths;
    return af.children.filter((c) => {
      if (!(c instanceof import_obsidian.TFolder))
        return false;
      if (c.name.startsWith("."))
        return false;
      return !skipped(c.path, skip);
    });
  }
  homeRooms() {
    return this.plugin.settings.rooms.filter((r) => !r.parent && !r.draft);
  }
  childrenOf(id) {
    return this.plugin.settings.rooms.filter(
      (r) => r.parent === id && r.id !== id && !r.draft
    );
  }
  isQuietLine(room, seen) {
    if (room.quiet)
      return true;
    if (!room.parent)
      return false;
    const visited = seen != null ? seen : /* @__PURE__ */ new Set();
    visited.add(room.id);
    if (visited.has(room.parent))
      return false;
    const parent = this.plugin.settings.rooms.find((r) => r.id === room.parent);
    return parent ? this.isQuietLine(parent, visited) : false;
  }
  liveFolders() {
    const out = [];
    for (const room of this.plugin.settings.rooms) {
      if (room.draft)
        continue;
      if (this.isQuietLine(room))
        continue;
      if (!room.folder)
        continue;
      out.push({
        id: room.id,
        folder: room.folder,
        kicker: room.kicker || room.name
      });
    }
    return out;
  }
  ownerOf(file, live) {
    let best;
    for (const room of live) {
      if (!inFolder(file, room.folder))
        continue;
      if (!best || room.folder.length > best.folder.length)
        best = room;
    }
    return best;
  }
  roomCount(room) {
    const kids = this.childrenOf(room.id);
    if (kids.length)
      return kids.length;
    if (room.folder)
      return this.mdIn(room.folder).length;
    return 0;
  }
  openRoom(room, parentLabel) {
    const kids = this.childrenOf(room.id);
    if (kids.length) {
      this.push({ type: "group", room });
      return;
    }
    if (room.folder) {
      this.push({
        type: "folder",
        title: room.name,
        folder: room.folder,
        kicker: room.kicker || room.name,
        parentLabel,
        pinBacklog: room.pinBacklog,
        maxNotes: room.maxNotes
      });
    }
  }
  async openNote(file) {
    await this.app.workspace.getLeaf("tab").openFile(file);
  }
  async createNamedNote(folder, raw) {
    const t = this.copy();
    const base = safeName(raw || (isInboxFolder(folder) ? inboxStamp() : t.untitled), t);
    let filename = base;
    let n = 2;
    while (this.app.vault.getAbstractFileByPath(folder + "/" + filename + ".md")) {
      filename = base + " " + n++;
    }
    try {
      const file = await this.app.vault.create(folder + "/" + filename + ".md", "");
      await this.openNote(file);
    } catch (e) {
      new import_obsidian.Notice(t.createFailed);
    }
  }
  async quickNote(folder) {
    if (!folder)
      return;
    if (!this.app.vault.getAbstractFileByPath(folder)) {
      new import_obsidian.Notice(this.copy().folderGone);
      return;
    }
    await this.createNamedNote(folder, inboxStamp());
  }
  async newNote(folder) {
    if (!folder)
      return;
    if (!this.app.vault.getAbstractFileByPath(folder)) {
      new import_obsidian.Notice(this.copy().folderGone);
      return;
    }
    const preset = isInboxFolder(folder) ? inboxStamp() : "";
    new NameModal(this.app, preset, this.copy(), (raw) => {
      void this.createNamedNote(folder, raw);
    }).open();
  }
  card(parent, spec, onClick) {
    const el = parent.createEl("div", {
      cls: "desk-card" + (spec.quiet ? " is-quiet" : "") + (spec.note ? " is-note" : "") + (spec.span2 ? " span-2" : ""),
      attr: onClick ? { role: "button", tabindex: "0" } : {}
    });
    if (spec.kicker)
      el.createEl("span", { cls: "desk-kicker", text: spec.kicker });
    else if (!spec.note)
      el.createEl("span", { cls: "desk-kicker", text: "\xA0" });
    if (spec.count !== void 0 && spec.count !== "" && spec.count !== null) {
      el.createEl("span", { cls: "desk-count", text: String(spec.count) });
    }
    el.createEl("strong", { text: spec.title });
    if (spec.line)
      el.createEl("span", { cls: "desk-line", text: spec.line });
    else if (!spec.note)
      el.createEl("span", { cls: "desk-line", text: "\xA0" });
    if (spec.onAdd) {
      const add = el.createEl("button", {
        cls: "desk-add",
        text: "+",
        attr: { type: "button", "aria-label": this.copy().addHere }
      });
      add.addEventListener("click", (e) => {
        var _a;
        e.preventDefault();
        e.stopPropagation();
        (_a = spec.onAdd) == null ? void 0 : _a.call(spec);
      });
    }
    if (onClick) {
      el.addEventListener("click", onClick);
      el.addEventListener("keydown", (e) => {
        if (e.key !== "Enter" && e.key !== " ")
          return;
        e.preventDefault();
        onClick();
      });
    } else {
      el.addClass("is-still");
    }
    return el;
  }
  nav(root, crumbs, folder) {
    const bar = root.createDiv({ cls: "an-tou-nav" });
    const trail = bar.createDiv({ cls: "an-tou-crumbs" });
    crumbs.forEach((c, i) => {
      if (i > 0)
        trail.createSpan({ text: " \xB7 " });
      const b = trail.createEl("button", { text: c.label });
      b.addEventListener("click", c.go);
    });
    if (folder) {
      const add = bar.createEl("button", {
        cls: "an-tou-add",
        text: "+",
        attr: { type: "button", "aria-label": this.copy().newNote }
      });
      add.addEventListener("click", (e) => {
        e.preventDefault();
        e.stopPropagation();
        void this.newNote(folder);
      });
    }
  }
  async render() {
    const seq = ++this.renderSeq;
    this.renderFiles = this.app.vault.getMarkdownFiles();
    try {
      const root = this.contentEl;
      root.empty();
      const inner = root.createDiv({ cls: "an-tou-inner" });
      const page = this.current();
      if (page.type === "welcome")
        this.renderWelcome(inner);
      else if (page.type === "home")
        await this.renderHome(inner, seq);
      else if (page.type === "group")
        this.renderGroup(inner, page.room);
      else if (page.type === "more")
        await this.renderMore(inner, page, seq);
      else
        await this.renderFolder(inner, page, seq);
    } finally {
      if (this.renderSeq === seq)
        this.renderFiles = null;
    }
  }
  topFolders() {
    const skip = this.plugin.settings.skipPaths;
    return this.app.vault.getRoot().children.filter(
      (c) => c instanceof import_obsidian.TFolder && !c.name.startsWith(".") && !skipped(c.path, skip)
    );
  }
  renderWelcome(inner) {
    const t = this.copy();
    inner.createEl("h1", { text: t.welcomeTitle });
    inner.createEl("p", { cls: "an-tou-lede", text: t.welcomeSub });
    const list = inner.createEl("ul", { cls: "an-tou-welcome-list" });
    for (const line of [t.welcomePoint1, t.welcomePoint2, t.welcomePoint3, t.welcomePoint4]) {
      list.createEl("li", { text: line });
    }
    const folders = this.topFolders();
    inner.createEl("p", { cls: "an-tou-lede", text: t.welcomePick(folders.length) });
    const picked = new Set(folders.slice(0, 6).map((f) => f.path));
    const chips = inner.createDiv({ cls: "an-tou-chips" });
    for (const folder of folders) {
      const chip = chips.createEl("button", {
        cls: "an-tou-chip" + (picked.has(folder.path) ? " is-on" : ""),
        text: folder.name,
        attr: { type: "button", "aria-pressed": picked.has(folder.path) ? "true" : "false" }
      });
      chip.addEventListener("click", () => {
        const on = picked.has(folder.path);
        if (on)
          picked.delete(folder.path);
        else
          picked.add(folder.path);
        chip.toggleClass("is-on", !on);
        chip.setAttribute("aria-pressed", on ? "false" : "true");
      });
    }
    const row = inner.createDiv({ cls: "an-tou-welcome-btns" });
    const all = row.createEl("button", { text: t.welcomeAddAll, attr: { type: "button" } });
    all.addEventListener("click", () => {
      void this.finishWelcome(null);
    });
    const go = row.createEl("button", {
      cls: "mod-cta",
      text: t.welcomeStart,
      attr: { type: "button" }
    });
    go.addEventListener("click", () => {
      void this.finishWelcome([...picked]);
    });
  }
  async finishWelcome(only) {
    const plugin = this.plugin;
    plugin.settings.rooms = only === null ? plugin.scanRooms() : plugin.scanRooms(only, false);
    plugin.settings.welcomed = true;
    await plugin.saveSettings();
    await this.resetHome();
  }
  async renderHome(inner, seq) {
    const title = this.plugin.settings.title || DEFAULT_TITLE;
    inner.createEl("h1", { text: title });
    inner.createEl("span", { cls: "an-tou-date", text: todayLabel(this.plugin.settings.uiLang) });
    const rooms = this.homeRooms();
    if (rooms.length === 0) {
      inner.createEl("p", {
        cls: "an-tou-lede",
        text: this.copy().emptyRooms
      });
      return;
    }
    const grid = inner.createDiv({ cls: "an-tou-grid" });
    for (const room of rooms) {
      const n = this.roomCount(room);
      this.card(
        grid,
        {
          kicker: room.kicker,
          count: room.quiet ? void 0 : n,
          title: room.name,
          line: room.line,
          quiet: room.quiet,
          onAdd: room.folder ? () => void this.quickNote(room.folder) : void 0
        },
        () => this.openRoom(room, title)
      );
    }
    inner.createEl("h2", { text: this.copy().recent });
    const recentGrid = inner.createDiv({ cls: "an-tou-grid" });
    const recent = this.recentNotes();
    const recentCopies = await Promise.all(recent.map((e) => noteCardCopy(this.app, e.file)));
    if (seq !== this.renderSeq)
      return;
    for (let i = 0; i < recent.length; i++) {
      const entry = recent[i];
      const file = entry.file;
      const copy = recentCopies[i];
      this.card(
        recentGrid,
        {
          kicker: entry.owner.kicker || "Note",
          title: copy.title,
          line: copy.line,
          note: true
        },
        () => {
          void this.openNote(file);
        }
      );
    }
  }
  recentNotes() {
    var _a;
    const live = this.liveFolders();
    const skip = this.plugin.settings.skipPaths;
    const all = (_a = this.renderFiles) != null ? _a : this.app.vault.getMarkdownFiles();
    const owned = [];
    for (const file of all) {
      if (skipped(file.path, skip))
        continue;
      if (file.basename === "BACKLOG" || file.basename.startsWith("BACKLOG"))
        continue;
      const owner = this.ownerOf(file, live);
      if (!owner)
        continue;
      owned.push({ file, owner });
    }
    const buckets = /* @__PURE__ */ new Map();
    for (const entry of owned) {
      const list = buckets.get(entry.owner.id) || [];
      list.push(entry);
      buckets.set(entry.owner.id, list);
    }
    for (const list of buckets.values()) {
      list.sort((a, b) => b.file.stat.mtime - a.file.stat.mtime);
    }
    const rooms = Array.from(buckets.values()).filter((list) => list.length).sort((a, b) => b[0].file.stat.mtime - a[0].file.stat.mtime);
    const picked = [];
    const seen = /* @__PURE__ */ new Set();
    for (const list of rooms) {
      if (picked.length >= RECENT_CAP)
        break;
      picked.push(list[0]);
      seen.add(list[0].file.path);
    }
    if (picked.length < RECENT_CAP) {
      const rest = owned.filter((e) => !seen.has(e.file.path)).sort((a, b) => b.file.stat.mtime - a.file.stat.mtime);
      for (const entry of rest) {
        if (picked.length >= RECENT_CAP)
          break;
        picked.push(entry);
      }
    }
    return picked;
  }
  renderGroup(inner, room) {
    const title = this.plugin.settings.title || DEFAULT_TITLE;
    this.nav(inner, [{ label: "\u2190 " + title, go: () => this.back() }]);
    inner.createEl("h1", { text: room.name });
    if (room.line)
      inner.createEl("p", { cls: "an-tou-lede", text: room.line });
    const grid = inner.createDiv({ cls: "an-tou-grid" });
    for (const child of this.childrenOf(room.id)) {
      const files = child.folder ? this.mdIn(child.folder, child.pinBacklog ? ["BACKLOG"] : []) : [];
      const n = this.roomCount(child);
      this.card(
        grid,
        {
          count: n,
          title: child.name,
          line: child.line || (n === 1 && files[0] ? titleOf(files[0]) : ""),
          quiet: this.isQuietLine(child),
          onAdd: child.folder ? () => void this.quickNote(child.folder) : void 0
        },
        () => this.openRoom(child, room.name)
      );
    }
  }
  async renderFolder(inner, page, seq) {
    const t = this.copy();
    const title = this.plugin.settings.title || DEFAULT_TITLE;
    const goHome = () => {
      this.stack = [{ type: "home" }];
      void this.render();
    };
    const crumbs = [{ label: "\u2190 " + page.parentLabel, go: () => this.back() }];
    if (page.parentLabel !== title)
      crumbs.push({ label: title, go: goHome });
    this.nav(inner, crumbs, page.folder);
    inner.createEl("h1", { text: page.title });
    const all = this.mdIn(page.folder);
    const backlog = all.find((f) => f.basename === "BACKLOG");
    const useBacklog = page.pinBacklog || !!backlog;
    const subs = this.subfolders(page.folder);
    if (useBacklog && backlog) {
      inner.createEl("p", { cls: "an-tou-lede", text: t.backlogLede });
      inner.createEl("h2", { text: t.mainFile });
      const top = inner.createDiv({ cls: "an-tou-grid" });
      this.card(
        top,
        { kicker: page.kicker, title: "Backlog", line: backlog.basename, span2: true },
        () => {
          void this.openNote(backlog);
        }
      );
    }
    if (subs.length && !useBacklog) {
      const grid2 = inner.createDiv({ cls: "an-tou-grid" });
      for (const folder of subs) {
        const n = this.mdIn(folder.path).length;
        this.card(grid2, { count: n, title: folder.name }, () => {
          this.push({
            type: "folder",
            title: folder.name,
            folder: folder.path,
            kicker: page.kicker,
            parentLabel: page.title
          });
        });
      }
    }
    let notes = all.filter((f) => f.basename !== "BACKLOG" && f.basename !== "BACKLOG-archive").sort((a, b) => b.stat.mtime - a.stat.mtime);
    const cap = page.maxNotes || (useBacklog ? 7 : notes.length > 40 ? 24 : notes.length);
    const rest = Math.max(0, notes.length - cap);
    if (rest)
      notes = notes.slice(0, cap);
    if (useBacklog)
      inner.createEl("h2", { text: t.recentSlips });
    const grid = inner.createDiv({ cls: "an-tou-grid" });
    const copies = await Promise.all(notes.map((f) => noteCardCopy(this.app, f)));
    if (seq !== this.renderSeq)
      return;
    for (let i = 0; i < notes.length; i++) {
      const file = notes[i];
      const copy = copies[i];
      this.card(
        grid,
        { kicker: page.kicker, title: copy.title, line: copy.line, note: true },
        () => {
          void this.openNote(file);
        }
      );
    }
    if (rest > 0) {
      this.card(
        grid,
        {
          title: t.more(rest),
          note: true,
          quiet: true
        },
        () => {
          this.push({
            type: "more",
            title: page.title,
            folder: page.folder,
            kicker: page.kicker,
            parentLabel: page.parentLabel,
            pinBacklog: page.pinBacklog,
            maxNotes: page.maxNotes,
            skip: cap
          });
        }
      );
    }
    if (!notes.length && !subs.length && !backlog) {
      inner.createEl("p", { cls: "an-tou-lede", text: t.emptyFolder });
    }
  }
  async renderMore(inner, page, seq) {
    const t = this.copy();
    this.nav(
      inner,
      [{ label: "\u2190 " + page.title, go: () => this.back() }],
      page.folder
    );
    inner.createEl("h1", { text: page.title });
    const notes = this.mdIn(page.folder).filter((f) => f.basename !== "BACKLOG" && f.basename !== "BACKLOG-archive").sort((a, b) => b.stat.mtime - a.stat.mtime).slice(page.skip);
    inner.createEl("p", {
      cls: "an-tou-lede",
      text: notes.length ? t.more(notes.length) : t.noMoreNotes
    });
    const grid = inner.createDiv({ cls: "an-tou-grid" });
    const copies = await Promise.all(notes.map((f) => noteCardCopy(this.app, f)));
    if (seq !== this.renderSeq)
      return;
    for (let i = 0; i < notes.length; i++) {
      const file = notes[i];
      const copy = copies[i];
      this.card(
        grid,
        { kicker: page.kicker, title: copy.title, line: copy.line, note: true },
        () => {
          void this.openNote(file);
        }
      );
    }
  }
};
var AnTouSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this._saveTimer = null;
    this._savePending = false;
    this.plugin = plugin;
  }
  copy() {
    return this.plugin.settings.uiLang === "en" ? COPY.en : COPY.zh;
  }
  display() {
    const { containerEl } = this;
    const t = this.copy();
    const lang = this.plugin.settings.uiLang === "en" ? "en" : "zh";
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName(t.language).setDesc(t.languageDesc).addButton((b) => {
      b.setButtonText(t.chinese).onClick(() => {
        void this.setLang("zh");
      });
      if (lang === "zh")
        b.setCta();
    }).addButton((b) => {
      b.setButtonText(t.english).onClick(() => {
        void this.setLang("en");
      });
      if (lang === "en")
        b.setCta();
    });
    new import_obsidian.Setting(containerEl).setName(t.desk).setHeading();
    new import_obsidian.Setting(containerEl).setName(t.title).setDesc(t.titleDesc).addText(
      (box) => box.setValue(this.plugin.settings.title).onChange((v) => {
        this.plugin.settings.title = v.trim() || DEFAULT_TITLE;
        this.debouncedSave();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.look).setDesc(t.lookDesc).addToggle(
      (box) => box.setValue(this.plugin.settings.applyLook !== false).onChange((v) => {
        this.plugin.settings.applyLook = v;
        this.plugin.applyLook();
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.serif).setDesc(t.serifDesc).addToggle(
      (box) => box.setValue(this.plugin.settings.applySerif !== false).onChange((v) => {
        this.plugin.settings.applySerif = v;
        this.plugin.applyLook();
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.hideRibbon).setDesc(t.hideRibbonDesc).addToggle(
      (box) => box.setValue(this.plugin.settings.hideRibbon === true).onChange((v) => {
        this.plugin.settings.hideRibbon = v;
        this.plugin.applyLook();
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.openOnStart).setDesc(t.openOnStartDesc).addToggle(
      (box) => box.setValue(this.plugin.settings.openOnStart).onChange((v) => {
        this.plugin.settings.openOnStart = v;
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.collapse).setDesc(t.collapseDesc).addToggle(
      (box) => box.setValue(this.plugin.settings.collapseExplorer).onChange((v) => {
        this.plugin.settings.collapseExplorer = v;
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.skip).setDesc(t.skipDesc).addText(
      (box) => box.setValue(this.plugin.settings.skipPaths.join(", ")).onChange((v) => {
        this.plugin.settings.skipPaths = v.split(",").map((s) => s.trim()).filter(Boolean);
        this.debouncedSave();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.rooms).setHeading();
    this.fillHelp(containerEl.createDiv({ cls: "an-tou-help-inline" }), t);
    new import_obsidian.Setting(containerEl).setDesc(t.roomsDesc).addButton(
      (b) => b.setButtonText(t.addRoom).onClick(() => {
        void this.addRoom();
      })
    ).addButton(
      (b) => b.setButtonText(t.fromVault).onClick(() => {
        void this.rebuildRooms();
      })
    );
    const drafts = this.plugin.settings.rooms.filter((r) => r.draft);
    const rest = this.plugin.settings.rooms.filter((r) => !r.draft);
    for (const room of drafts.concat(rest)) {
      this.drawRoom(containerEl, room, t);
    }
  }
  async setLang(uiLang) {
    this.plugin.settings.uiLang = uiLang;
    await this.plugin.saveSettings();
    this.display();
  }
  async saveAndRefresh() {
    if (this._saveTimer !== null) {
      window.clearTimeout(this._saveTimer);
      this._saveTimer = null;
    }
    this._savePending = false;
    await this.plugin.saveSettings();
    this.plugin.refreshDesks();
  }
  debouncedSave() {
    this._savePending = true;
    if (this._saveTimer !== null)
      window.clearTimeout(this._saveTimer);
    this._saveTimer = window.setTimeout(() => {
      void this.saveAndRefresh();
    }, 400);
  }
  hide() {
    const pending = this._savePending;
    if (this._saveTimer !== null) {
      window.clearTimeout(this._saveTimer);
      this._saveTimer = null;
    }
    this._savePending = false;
    if (pending)
      void this.saveAndRefresh();
  }
  async addRoom() {
    const t = this.copy();
    this.plugin.settings.rooms.unshift({
      id: "room-" + Date.now().toString(36),
      name: t.newRoom,
      draft: true
    });
    await this.saveAndRefresh();
    this.display();
  }
  async saveRoom(id) {
    const rooms = this.plugin.settings.rooms;
    const i = rooms.findIndex((r) => r.id === id);
    if (i < 0)
      return;
    const t = this.copy();
    const name = (rooms[i].name || "").trim();
    if (!name || name === t.newRoom) {
      new import_obsidian.Notice(t.nameRequired);
      return;
    }
    const [room] = rooms.splice(i, 1);
    delete room.draft;
    rooms.push(room);
    await this.saveAndRefresh();
    this.display();
  }
  async rebuildRooms() {
    this.plugin.settings.rooms = this.plugin.mergeRooms(this.plugin.scanRooms());
    await this.saveAndRefresh();
    this.display();
    new import_obsidian.Notice(this.copy().fromVaultNotice);
  }
  drawRoom(containerEl, room, t) {
    const details = containerEl.createEl("details", {
      cls: "an-tou-room-edit" + (room.draft ? " is-draft" : "")
    });
    if (room.draft)
      details.open = true;
    const summary = details.createEl("summary", { cls: "an-tou-room-summary" });
    summary.createSpan({ cls: "an-tou-room-caret", text: "\u25B8" });
    const nameEl = summary.createSpan({
      cls: "an-tou-room-name",
      text: room.name || t.newRoom
    });
    const role = this.roomRole(room, t);
    const roleEl = summary.createSpan({
      cls: "an-tou-room-role" + (role.bad ? " is-bad" : ""),
      text: role.text
    });
    const syncSummary = () => {
      nameEl.setText(room.name || t.newRoom);
      const next = this.roomRole(room, t);
      roleEl.setText(next.text);
      roleEl.toggleClass("is-bad", next.bad);
    };
    const actions = summary.createDiv({ cls: "an-tou-room-actions" });
    if (room.draft) {
      const save = actions.createEl("button", {
        cls: "an-tou-room-save mod-cta",
        text: t.saveRoom,
        attr: { type: "button" }
      });
      save.addEventListener("click", (e) => {
        e.preventDefault();
        e.stopPropagation();
        void this.saveRoom(room.id);
      });
    }
    const del = actions.createEl("button", {
      cls: "an-tou-room-del",
      attr: { type: "button", "aria-label": t.remove, title: t.remove }
    });
    (0, import_obsidian.setIcon)(del, "trash");
    del.addEventListener("click", (e) => {
      e.preventDefault();
      e.stopPropagation();
      this.confirmRemove(room, t);
    });
    details.createDiv({ cls: "an-tou-room-id", text: t.roomId + " \xB7 " + room.id });
    const grid = details.createDiv({ cls: "an-tou-room-grid" });
    this.textField(grid, t.name, t.nameDesc, room.name, (v) => {
      room.name = v;
      syncSummary();
    });
    this.folderField(grid, room, t, syncSummary);
    this.textField(grid, t.kicker, t.kickerDesc, room.kicker || "", (v) => {
      room.kicker = v;
    });
    this.textField(grid, t.line, t.lineDesc, room.line || "", (v) => {
      room.line = v;
    });
    this.parentField(grid, room, t);
    {
      const setting = new import_obsidian.Setting(grid).setName(t.maxNotes).setDesc(t.maxNotesDesc);
      setting.addText((box) => {
        const apply = (v) => {
          const raw = v.trim();
          const num = Number(raw);
          const ok = raw === "" || Number.isInteger(num) && num > 0;
          room.maxNotes = ok && raw !== "" ? num : void 0;
          this.showFieldError(setting, box.inputEl, ok ? "" : t.maxNotesBad);
          this.debouncedSave();
        };
        box.setValue(room.maxNotes ? String(room.maxNotes) : "").onChange(apply);
      });
    }
    new import_obsidian.Setting(grid).setName(t.quiet).setDesc(t.quietDesc).addToggle(
      (box) => box.setValue(!!room.quiet).onChange((v) => {
        room.quiet = v;
        void this.saveAndRefresh();
      })
    );
    if (this.hasBacklogFile(room)) {
      new import_obsidian.Setting(grid).setName(t.backlogNote).setDesc(t.backlogNoteDesc);
    } else {
      new import_obsidian.Setting(grid).setName(t.pinBacklog).setDesc(t.pinBacklogDesc).addToggle(
        (box) => box.setValue(!!room.pinBacklog).onChange((v) => {
          room.pinBacklog = v;
          void this.saveAndRefresh();
        })
      );
    }
  }
  hasBacklogFile(room) {
    if (!room.folder)
      return false;
    const f = this.app.vault.getAbstractFileByPath(room.folder + "/BACKLOG.md");
    return f instanceof import_obsidian.TFile;
  }
  roomRole(room, t) {
    if (room.draft)
      return { text: t.draftHint, bad: false };
    if (room.stale)
      return { text: t.staleFolder, bad: true };
    if (room.parent) {
      const parent = this.plugin.settings.rooms.find((r) => r.id === room.parent);
      if (!parent)
        return { text: t.roleParentMissing, bad: true };
      return { text: t.roleNested.replace("{name}", parent.name || parent.id), bad: false };
    }
    const kids = this.childrenIds(room.id).length;
    if (kids) {
      let text = t.roleGroup.replace("{n}", String(kids));
      if (room.folder)
        text += t.roleGroupHidden.replace("{folder}", room.folder);
      return { text, bad: false };
    }
    if (room.folder)
      return { text: t.roleHome.replace("{folder}", room.folder), bad: false };
    return { text: t.roleNoFolder, bad: true };
  }
  childrenIds(id) {
    return this.plugin.settings.rooms.filter((r) => r.parent === id && r.id !== id && !r.draft).map((r) => r.id);
  }
  blockedParentIds(room) {
    const blocked = /* @__PURE__ */ new Set();
    const walk = (id) => {
      if (blocked.has(id))
        return;
      blocked.add(id);
      for (const r of this.plugin.settings.rooms) {
        if (r.parent === id && r.id !== id)
          walk(r.id);
      }
    };
    walk(room.id);
    return blocked;
  }
  async changeParent(room, value) {
    room.parent = value || void 0;
    await this.saveAndRefresh();
    this.display();
  }
  parentField(grid, room, t) {
    new import_obsidian.Setting(grid).setName(t.parent).setDesc(t.parentDesc).addDropdown((dd) => {
      var _a, _b;
      dd.addOption("", t.parentNone);
      const blocked = this.blockedParentIds(room);
      const rooms = this.plugin.settings.rooms;
      const candidates = rooms.filter((r) => !r.draft && !blocked.has(r.id));
      const counts = /* @__PURE__ */ new Map();
      for (const r of candidates)
        counts.set(r.name, ((_a = counts.get(r.name)) != null ? _a : 0) + 1);
      for (const r of candidates) {
        const dup = ((_b = counts.get(r.name)) != null ? _b : 0) > 1;
        dd.addOption(r.id, dup ? r.name + " \xB7 " + r.id : r.name);
      }
      const current = room.parent || "";
      if (current && !candidates.some((r) => r.id === current)) {
        const known = rooms.find((r) => r.id === current);
        dd.addOption(
          current,
          known ? t.parentUnselectable.replace("{name}", known.name || known.id) : t.parentMissing.replace("{id}", current)
        );
      }
      dd.setValue(current);
      dd.onChange((v) => {
        void this.changeParent(room, v);
      });
    });
  }
  folderField(grid, room, t, sync) {
    const setting = new import_obsidian.Setting(grid).setName(t.folder).setDesc(t.folderDesc);
    setting.addText((box) => {
      const apply = (v) => {
        room.folder = v.trim() || void 0;
        this.showFolderError(setting, box.inputEl, v);
        sync();
        this.debouncedSave();
      };
      box.setValue(room.folder || "").onChange(apply);
      new FolderSuggest(this.app, box.inputEl, (picked) => apply(picked));
      this.showFolderError(setting, box.inputEl, room.folder || "");
    });
  }
  showFieldError(setting, inputEl, message) {
    const prev = setting.settingEl.querySelector(".an-tou-field-error");
    if (prev)
      prev.remove();
    if (!message) {
      inputEl.removeClass("is-invalid");
      return;
    }
    inputEl.addClass("is-invalid");
    setting.settingEl.createDiv({ cls: "an-tou-field-error", text: message });
  }
  showFolderError(setting, inputEl, raw) {
    const path = raw.trim();
    const prev = setting.settingEl.querySelector(".an-tou-field-error");
    if (prev)
      prev.remove();
    if (!path) {
      inputEl.removeClass("is-invalid");
      return;
    }
    const folders = this.app.vault.getAllFolders(false).map((f) => f.path);
    if (folders.indexOf(path) !== -1) {
      inputEl.removeClass("is-invalid");
      return;
    }
    inputEl.addClass("is-invalid");
    const t = this.copy();
    const box = setting.settingEl.createDiv({ cls: "an-tou-field-error" });
    box.createDiv({ text: t.folderMissing });
    const near = closestFolder(path, folders);
    if (near)
      box.createDiv({ text: t.folderDidYouMean.replace("{folder}", near) });
  }
  confirmRemove(room, t) {
    const kids = this.plugin.settings.rooms.filter(
      (r) => r.parent === room.id && r.id !== room.id
    ).length;
    const lines = [];
    if (kids)
      lines.push(t.deleteHolds.replace("{n}", String(kids)));
    lines.push(t.deleteNotesSafe);
    new ConfirmModal(this.app, {
      title: t.deleteTitle.replace("{name}", room.name || t.newRoom),
      lines,
      confirm: t.deleteConfirm,
      cancel: t.deleteCancel,
      onConfirm: () => {
        void this.removeRoom(room.id);
      }
    }).open();
  }
  textField(parent, name, desc, value, assign) {
    new import_obsidian.Setting(parent).setName(name).setDesc(desc).addText(
      (box) => box.setValue(value).onChange((v) => {
        assign(v);
        this.debouncedSave();
      })
    );
  }
  fillHelp(pop, t) {
    pop.createDiv({ cls: "an-tou-help-kicker-line", text: t.helpTitle });
    const demo = pop.createDiv({ cls: "an-tou-help-demo" });
    const card = demo.createDiv({ cls: "an-tou-help-card" });
    card.createSpan({ cls: "an-tou-help-kicker", text: "Inbox" });
    card.createSpan({ cls: "an-tou-help-count", text: "3" });
    card.createEl("strong", { text: t.sampleName });
    card.createSpan({ cls: "an-tou-help-line", text: t.sampleLine });
    const keys = demo.createDiv({ cls: "an-tou-help-keys" });
    const addKey = (cls, cap, sample) => {
      const row = keys.createDiv({ cls: "an-tou-help-key" });
      row.createSpan({ cls: "an-tou-help-swatch " + cls });
      row.createSpan({ text: cap + " \xB7 " + sample });
    };
    addKey("is-kicker", t.helpKickerCap, "Inbox");
    addKey("is-name", t.helpNameCap, t.sampleName);
    addKey("is-line", t.helpLineCap, t.sampleLine);
    addKey("is-folder", t.helpFolderCap, "00-Inbox");
    addKey("is-count", t.helpCountCap, "3");
    pop.createDiv({ cls: "an-tou-help-note", text: t.helpFolderNote });
    const nest = pop.createDiv({ cls: "an-tou-help-nest" });
    nest.createDiv({ cls: "an-tou-help-kicker-line", text: t.helpParentCap });
    const home = nest.createDiv({ cls: "an-tou-help-flow" });
    home.createSpan({ cls: "an-tou-help-chip", text: t.helpHome });
    const cab = home.createDiv({ cls: "an-tou-help-mini" });
    cab.createSpan({ cls: "an-tou-help-kicker", text: "Cabinet" });
    cab.createEl("strong", { text: t.sampleCabinet });
    cab.createSpan({ cls: "an-tou-help-id", text: "cabinet" });
    home.createSpan({ cls: "an-tou-help-arrow", text: "\u2193" });
    home.createSpan({ cls: "an-tou-help-chip", text: t.helpInside });
    const child = home.createDiv({ cls: "an-tou-help-mini" });
    child.createSpan({ cls: "an-tou-help-kicker", text: "Thinking" });
    child.createEl("strong", { text: t.sampleThinking });
    child.createSpan({ cls: "an-tou-help-id", text: "cabinet" });
    nest.createDiv({ cls: "an-tou-help-note", text: t.helpParentNote });
    pop.createDiv({ cls: "an-tou-help-note", text: t.helpQuietNote });
  }
  async removeRoom(id) {
    this.plugin.settings.rooms = this.plugin.settings.rooms.filter((r) => r.id !== id);
    for (const room of this.plugin.settings.rooms) {
      if (room.parent === id)
        delete room.parent;
    }
    await this.saveAndRefresh();
    this.display();
  }
};
var AnTouPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = JSON.parse(JSON.stringify(DEFAULT_SETTINGS));
  }
  async onload() {
    const saved = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, saved != null ? saved : {});
    this.settings.rooms = Array.isArray(this.settings.rooms) ? this.settings.rooms.slice() : [];
    this.settings.skipPaths = Array.isArray(this.settings.skipPaths) ? this.settings.skipPaths.slice() : [];
    if (!Array.isArray(this.settings.rooms))
      this.settings.rooms = [];
    if (!Array.isArray(this.settings.skipPaths))
      this.settings.skipPaths = [];
    if (this.settings.uiLang !== "en")
      this.settings.uiLang = "zh";
    if (!this.settings.title || this.settings.title === "An Tou") {
      this.settings.title = DEFAULT_TITLE;
    }
    let migrated = false;
    if (saved && typeof saved.applySerif === "undefined") {
      this.settings.applySerif = this.settings.applyLook !== false;
      migrated = true;
    }
    if (saved && typeof saved.hideRibbon === "undefined") {
      this.settings.hideRibbon = false;
      migrated = true;
    }
    if (migrated)
      await this.saveSettings();
    if (this.settings.skipSeeded !== true) {
      if (!this.settings.skipPaths.includes("attachments")) {
        this.settings.skipPaths.push("attachments");
      }
      this.settings.skipSeeded = true;
      await this.saveSettings();
    }
    this.registerView(VIEW_TYPE, (leaf) => new DeskView(leaf, this));
    this.addCommand({
      id: "open-desk",
      name: "Open desk",
      callback: () => {
        void this.activateView();
      }
    });
    this.addSettingTab(new AnTouSettingTab(this.app, this));
    this.applyLook();
    this.app.workspace.onLayoutReady(async () => {
      const fresh = this.settings.rooms.length === 0 && this.settings.welcomed !== true;
      if (!fresh && this.settings.welcomed !== true) {
        this.settings.welcomed = true;
        await this.saveSettings();
      }
      if (fresh) {
        await this.activateView("welcome");
        return;
      }
      if (this.settings.rooms.length === 0) {
        this.settings.rooms = this.scanRooms();
        await this.saveSettings();
      }
      if (this.settings.openOnStart)
        void this.activateView();
    });
  }
  onunload() {
    document.body.removeClass("an-tou-look", "an-tou-serif", "an-tou-hide-ribbon");
  }
  applyLook() {
    const body = document.body;
    body.toggleClass("an-tou-look", this.settings.applyLook !== false);
    body.toggleClass("an-tou-serif", this.settings.applySerif !== false);
    body.toggleClass("an-tou-hide-ribbon", this.settings.hideRibbon === true);
  }
  scanRooms(only, withSubs = true) {
    const rooms = [];
    const used = /* @__PURE__ */ new Set();
    const skip = this.settings.skipPaths;
    const copy = this.settings.uiLang === "en" ? COPY.en : COPY.zh;
    const files = this.app.vault.getMarkdownFiles();
    const root = this.app.vault.getRoot();
    for (const child of root.children) {
      if (!(child instanceof import_obsidian.TFolder))
        continue;
      if (child.name.startsWith("."))
        continue;
      if (skipped(child.path, skip))
        continue;
      if (only && !only.includes(child.path))
        continue;
      const id = uniqueId(slug(child.name), used);
      const n = this.mdCount(child.path, files);
      const room = {
        id,
        name: child.name,
        folder: child.path,
        kicker: kickerOf(child.name)
      };
      const line = noteCountLine(n, copy);
      if (line)
        room.line = line;
      rooms.push(room);
      if (!withSubs)
        continue;
      for (const sub of child.children) {
        if (!(sub instanceof import_obsidian.TFolder))
          continue;
        if (sub.name.startsWith("."))
          continue;
        if (skipped(sub.path, skip))
          continue;
        const sid = uniqueId(slug(sub.name), used);
        const sn = this.mdCount(sub.path, files);
        const childRoom = {
          id: sid,
          name: sub.name,
          folder: sub.path,
          kicker: kickerOf(sub.name),
          parent: id
        };
        const childLine = noteCountLine(sn, copy);
        if (childLine)
          childRoom.line = childLine;
        rooms.push(childRoom);
      }
    }
    return rooms;
  }
  mdCount(folder, files) {
    const skip = this.settings.skipPaths;
    const all = files != null ? files : this.app.vault.getMarkdownFiles();
    return all.filter((f) => {
      if (!inFolder(f, folder))
        return false;
      if (skipped(f.path, skip))
        return false;
      return true;
    }).length;
  }
  mergeRooms(scanned) {
    const all = this.settings.rooms.slice();
    const usedIds = new Set(all.map((r) => r.id));
    const byFolder = /* @__PURE__ */ new Map();
    for (const room of all) {
      if (room.folder)
        byFolder.set(room.folder, room);
    }
    const idMap = /* @__PURE__ */ new Map();
    for (const s of scanned) {
      if (!s.folder)
        continue;
      const hit = byFolder.get(s.folder);
      if (hit)
        idMap.set(s.id, hit.id);
    }
    for (const s of scanned) {
      if (s.parent || !s.folder || idMap.has(s.id))
        continue;
      const prefix = s.folder + "/";
      const parents = /* @__PURE__ */ new Set();
      for (const room of all) {
        if (!room.folder || !room.folder.startsWith(prefix))
          continue;
        if (room.parent)
          parents.add(room.parent);
      }
      if (parents.size !== 1)
        continue;
      const pid = [...parents][0];
      idMap.set(s.id, pid);
      const parent = all.find((r) => r.id === pid);
      if (!parent)
        continue;
      if (!parent.folder)
        parent.folder = s.folder;
      if (isAutoKicker(parent))
        parent.kicker = s.kicker;
      if (isAutoLine(parent.line))
        parent.line = s.line;
    }
    for (const s of scanned) {
      const eid = idMap.get(s.id);
      if (!eid)
        continue;
      const ex = all.find((r) => r.id === eid);
      if (!ex)
        continue;
      if (isAutoKicker(ex))
        ex.kicker = s.kicker;
      if (isAutoLine(ex.line))
        ex.line = s.line;
    }
    for (const s of scanned) {
      if (idMap.has(s.id))
        continue;
      let parent = s.parent;
      if (parent) {
        const mapped = idMap.get(parent);
        if (mapped)
          parent = mapped;
      }
      const id = uniqueId(s.id, usedIds);
      idMap.set(s.id, id);
      const room = { ...s, id };
      if (parent)
        room.parent = parent;
      else
        delete room.parent;
      all.push(room);
      if (room.folder)
        byFolder.set(room.folder, room);
    }
    const hasKids = new Set(all.map((r) => r.parent).filter(Boolean));
    for (const room of all) {
      if (!room.folder || hasKids.has(room.id)) {
        delete room.stale;
        continue;
      }
      const here = this.app.vault.getAbstractFileByPath(room.folder);
      if (here instanceof import_obsidian.TFolder)
        delete room.stale;
      else
        room.stale = true;
    }
    return all;
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  refreshDesks() {
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE)) {
      const view = leaf.view;
      if (!(view instanceof DeskView))
        continue;
      if (view.isShownNow())
        void view.render();
      else
        view.dirty = true;
    }
  }
  async activateView(start) {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE)[0];
    if (!leaf) {
      leaf = workspace.getLeaf("tab");
      await leaf.setViewState({ type: VIEW_TYPE, active: true });
    }
    if (start === "welcome") {
      const view = leaf.view;
      if (view instanceof DeskView) {
        view.stack = [{ type: "welcome" }];
        void view.render();
      }
    }
    await workspace.revealLeaf(leaf);
    if (this.settings.collapseExplorer && workspace.leftSplit) {
      workspace.leftSplit.collapse();
    }
  }
};
