/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AnTouPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE = "an-tou-desk";
var DEFAULT_SETTINGS = {
  title: "An Tou",
  openOnStart: true,
  collapseExplorer: true,
  applyLook: true,
  skipPaths: [],
  rooms: [],
  uiLang: "zh"
};
var COPY = {
  zh: {
    language: "\u754C\u9762\u8BED\u8A00",
    languageDesc: "\u53EA\u6539\u8BBE\u7F6E\u9875\u7684\u8BF4\u660E\u3002\u4E66\u684C\u5361\u7247\u4E0A\u7684\u4E2D\u6587\u6807\u9898\u8FD8\u662F\u4F60\u81EA\u5DF1\u586B\u7684\u3002",
    chinese: "\u4E2D\u6587",
    english: "English",
    desk: "\u4E66\u684C",
    title: "\u4E66\u684C\u6807\u9898",
    titleDesc: "\u9996\u9875\u6700\u5927\u90A3\u884C\u5B57\uFF0C\u4E5F\u663E\u793A\u5728\u6807\u7B7E\u4E0A\u3002",
    look: "\u6362\u4E0A\u8FD9\u5957\u5916\u89C2",
    lookDesc: "\u8584\u8377\u7EFF\u5E95\u548C\u886C\u7EBF\u5B57\u3002\u5173\u6389\u5C31\u53EA\u7559\u5361\u7247\u4E66\u684C\uFF0C\u989C\u8272\u4ECD\u7528\u4F60\u73B0\u5728\u7684\u4E3B\u9898\u3002",
    openOnStart: "\u6253\u5F00\u5E93\u65F6\u8FDB\u5165\u4E66\u684C",
    openOnStartDesc: "\u542F\u52A8\u65F6\u6253\u5F00\u4E66\u684C\uFF0C\u800C\u4E0D\u662F\u4E0A\u6B21\u90A3\u7BC7\u7B14\u8BB0\u3002",
    collapse: "\u6536\u8D77\u6587\u4EF6\u5217\u8868",
    collapseDesc: "\u6253\u5F00\u4E66\u684C\u65F6\u628A\u5DE6\u8FB9\u6587\u4EF6\u6811\u6536\u8D77\u6765\u3002",
    skip: "\u8DF3\u8FC7\u8FD9\u4E9B\u8DEF\u5F84",
    skipDesc: "\u7528\u9017\u53F7\u5206\u9694\u3002\u8FD9\u4E9B\u6587\u4EF6\u5939\u4E0D\u4F1A\u51FA\u73B0\u5728\u5361\u7247\u548C\u300C\u6700\u8FD1\u300D\u91CC\u3002",
    rooms: "\u623F\u95F4",
    roomsDesc: "\u6BCF\u5F20\u5361\u7247\u662F\u4E00\u4E2A\u623F\u95F4\u3002\u586B\u6587\u4EF6\u5939\u5C31\u8FDB\u90A3\u4E2A\u76EE\u5F55\uFF1B\u4E0D\u586B\u6587\u4EF6\u5939\uFF0C\u53EA\u586B\u5B50\u623F\u95F4\u7684\u300C\u7236\u623F\u95F4\u7F16\u53F7\u300D\uFF0C\u8FD9\u4E00\u5F20\u5C31\u662F\u5206\u7EC4\u3002",
    addRoom: "\u6DFB\u52A0\u623F\u95F4",
    fromVault: "\u6309\u5E93\u6839\u76EE\u5F55\u751F\u6210",
    fromVaultNotice: "\u5DF2\u6309\u9876\u5C42\u6587\u4EF6\u5939\u91CD\u5EFA\u623F\u95F4\u3002",
    roomId: "\u7F16\u53F7",
    remove: "\u5220\u9664\u8FD9\u4E2A\u623F\u95F4",
    name: "\u540D\u79F0",
    nameDesc: "\u5361\u7247\u4E2D\u95F4\u7684\u5927\u6807\u9898\u3002",
    folder: "\u6587\u4EF6\u5939",
    folderDesc: "\u5E93\u91CC\u7684\u8DEF\u5F84\uFF0C\u6BD4\u5982 00-Inbox\u3002\u7559\u7A7A\u5219\u8FD9\u5F20\u5361\u662F\u5206\u7EC4\u3002",
    kicker: "\u89D2\u6807",
    kickerDesc: "\u5361\u7247\u5DE6\u4E0A\u89D2\u90A3\u4E00\u5C0F\u884C\uFF0C\u6BD4\u5982 Inbox\u3002",
    line: "\u8BF4\u660E",
    lineDesc: "\u5361\u7247\u5E95\u4E0B\u90A3\u4E00\u884C\uFF0C\u5199\u8FD9\u683C\u662F\u5E72\u4EC0\u4E48\u7684\u3002",
    parent: "\u7236\u623F\u95F4\u7F16\u53F7",
    parentDesc: "\u586B\u4E0A\u4E00\u7EA7\u7684\u7F16\u53F7\uFF0C\u6BD4\u5982 cabinet\u3002\u586B\u4E86\u5C31\u4E0D\u51FA\u73B0\u5728\u9996\u9875\u3002",
    quiet: "\u5B89\u9759",
    quietDesc: "\u6253\u5F00\u540E\u5361\u7247\u53D8\u6DE1\uFF0C\u91CC\u9762\u7684\u7B14\u8BB0\u4E5F\u4E0D\u8FDB\u300C\u6700\u8FD1\u300D\u3002",
    newRoom: "\u65B0\u623F\u95F4"
  },
  en: {
    language: "Language",
    languageDesc: "Settings copy only. Card titles stay whatever you typed.",
    chinese: "\u4E2D\u6587",
    english: "English",
    desk: "Desk",
    title: "Desk title",
    titleDesc: "The large heading on the home cards and the tab.",
    look: "Apply this look",
    lookDesc: "Mint paper and serif type. Off keeps the cards and your current theme.",
    openOnStart: "Open on start",
    openOnStartDesc: "Show the desk when the vault opens, instead of the last note.",
    collapse: "Collapse file explorer",
    collapseDesc: "Fold the left file tree when the desk opens.",
    skip: "Skip these paths",
    skipDesc: "Comma-separated folder prefixes hidden from cards and recents.",
    rooms: "Rooms",
    roomsDesc: "Each card is a room. Point it at a folder, or leave the folder empty and nest child rooms under its id.",
    addRoom: "Add room",
    fromVault: "Build from top-level folders",
    fromVaultNotice: "Rooms rebuilt from top-level folders.",
    roomId: "Id",
    remove: "Remove this room",
    name: "Name",
    nameDesc: "The large title in the middle of the card.",
    folder: "Folder",
    folderDesc: "A vault path such as 00-Inbox. Leave empty to make a group.",
    kicker: "Kicker",
    kickerDesc: "The small line at the top-left of the card, such as Inbox.",
    line: "Line",
    lineDesc: "The sentence under the title, what this room is for.",
    parent: "Parent room id",
    parentDesc: "The id of the parent room, such as cabinet. Then it leaves the home grid.",
    quiet: "Quiet",
    quietDesc: "Fades the card and keeps its notes out of recents.",
    newRoom: "New room"
  }
};
function slug(name) {
  const s = name.toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]+/g, "-").replace(/^-|-$/g, "");
  return s || "room-" + Date.now().toString(36);
}
function inFolder(file, folder) {
  if (!folder)
    return false;
  return file.path === folder + ".md" || file.path.startsWith(folder + "/");
}
function skipped(path, skipPaths) {
  if (path.includes("/attachments/"))
    return true;
  return skipPaths.some((s) => path === s || path.startsWith(s + "/"));
}
function titleOf(file) {
  if (/^\d{4}-\d{2}-\d{2}\b/.test(file.basename) || /quick$/i.test(file.basename))
    return "";
  if (file.basename === "BACKLOG")
    return "Backlog";
  return file.basename;
}
function todayLabel() {
  const lang = document.documentElement.lang || navigator.language || "zh-CN";
  const tag = lang.toLowerCase().startsWith("zh") ? "zh-CN" : lang;
  return new Date().toLocaleDateString(tag, { month: "long", day: "numeric" });
}
function twoDigits(n) {
  return (n < 10 ? "0" : "") + String(n);
}
function inboxStamp() {
  const d = new Date();
  return `${d.getFullYear()}-${twoDigits(d.getMonth() + 1)}-${twoDigits(d.getDate())} ${twoDigits(d.getHours())}${twoDigits(d.getMinutes())}`;
}
function safeName(name) {
  return name.replace(/[\\/:*?"<>|]/g, "").replace(/\s+/g, " ").trim() || "\u672A\u547D\u540D";
}
function isInboxFolder(folder) {
  return /inbox/i.test(folder);
}
async function firstLine(app, file) {
  try {
    let t = await app.vault.cachedRead(file);
    if (t.startsWith("---")) {
      const end = t.indexOf("\n---", 3);
      if (end !== -1)
        t = t.slice(end + 4);
    }
    for (const raw of t.split("\n")) {
      let ln = raw.trim();
      if (!ln || ln.startsWith("#") || ln.startsWith("!") || ln.startsWith(">"))
        continue;
      if (ln.startsWith("```") || ln.startsWith("`"))
        continue;
      ln = ln.replace(/`[^`]+`/g, "").replace(/\s+/g, " ").trim();
      if (ln.length < 4)
        continue;
      return ln.slice(0, 36);
    }
  } catch (e) {
  }
  return "";
}
var NameModal = class extends import_obsidian.Modal {
  constructor(app, preset, onSubmit) {
    super(app);
    this.preset = preset || "";
    this.onSubmit = onSubmit;
  }
  onOpen() {
    this.titleEl.setText("\u65B0\u7B14\u8BB0");
    const input = this.contentEl.createEl("input", { type: "text", cls: "prompt-input" });
    input.value = this.preset;
    input.placeholder = "\u8FD9\u7BC7\u53EB\u4EC0\u4E48";
    input.addEventListener("keydown", (e) => {
      if (e.key !== "Enter")
        return;
      e.preventDefault();
      const v = input.value.trim();
      this.close();
      this.onSubmit(v);
    });
    window.setTimeout(() => {
      input.focus();
      if (this.preset)
        input.select();
    }, 20);
  }
};
var DeskView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.stack = [{ type: "home" }];
    this._tid = 0;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return this.plugin.settings.title || "An Tou";
  }
  getIcon() {
    return "layout-grid";
  }
  async onOpen() {
    this.contentEl.addClass("an-tou-view");
    this.registerEvent(this.app.vault.on("create", () => this.safeRender()));
    this.registerEvent(this.app.vault.on("delete", () => this.safeRender()));
    this.registerEvent(this.app.vault.on("rename", () => this.safeRender()));
    this.registerEvent(this.app.vault.on("modify", () => this.safeRender()));
    await this.render();
  }
  async onClose() {
    this.contentEl.empty();
  }
  safeRender() {
    if (this._tid)
      window.clearTimeout(this._tid);
    this._tid = window.setTimeout(() => {
      void this.render();
    }, 200);
  }
  resetHome() {
    this.stack = [{ type: "home" }];
    return this.render();
  }
  current() {
    return this.stack[this.stack.length - 1];
  }
  push(page) {
    this.stack.push(page);
    void this.render();
  }
  back() {
    if (this.stack.length > 1) {
      this.stack.pop();
      void this.render();
    }
  }
  mdIn(folder, extraSkip = []) {
    if (!folder)
      return [];
    const skip = this.plugin.settings.skipPaths;
    return this.app.vault.getMarkdownFiles().filter((f) => {
      if (!inFolder(f, folder))
        return false;
      if (skipped(f.path, skip))
        return false;
      return !extraSkip.some((s) => f.path.endsWith(s) || f.basename === s);
    });
  }
  subfolders(folder) {
    const af = this.app.vault.getAbstractFileByPath(folder);
    if (!(af instanceof import_obsidian.TFolder))
      return [];
    const skip = this.plugin.settings.skipPaths;
    return af.children.filter((c) => {
      if (!(c instanceof import_obsidian.TFolder))
        return false;
      if (c.name.startsWith("."))
        return false;
      return !skipped(c.path, skip);
    });
  }
  homeRooms() {
    return this.plugin.settings.rooms.filter((r) => !r.parent);
  }
  childrenOf(id) {
    return this.plugin.settings.rooms.filter((r) => r.parent === id);
  }
  isQuietLine(room) {
    if (room.quiet)
      return true;
    if (!room.parent)
      return false;
    const parent = this.plugin.settings.rooms.find((r) => r.id === room.parent);
    return parent ? this.isQuietLine(parent) : false;
  }
  liveFolders() {
    const out = [];
    for (const room of this.plugin.settings.rooms) {
      if (this.isQuietLine(room))
        continue;
      if (!room.folder)
        continue;
      out.push({ folder: room.folder, kicker: room.name });
    }
    return out;
  }
  roomCount(room) {
    const kids = this.childrenOf(room.id);
    if (kids.length)
      return kids.length;
    if (room.folder)
      return this.mdIn(room.folder).length;
    return 0;
  }
  openRoom(room, parentLabel) {
    const kids = this.childrenOf(room.id);
    if (kids.length) {
      this.push({ type: "group", room });
      return;
    }
    if (room.folder) {
      this.push({
        type: "folder",
        title: room.name,
        folder: room.folder,
        kicker: room.kicker || room.name,
        parentLabel,
        pinBacklog: room.pinBacklog,
        maxNotes: room.maxNotes
      });
    }
  }
  async openNote(file) {
    await this.app.workspace.getLeaf("tab").openFile(file);
  }
  async createNamedNote(folder, raw) {
    const base = safeName(raw || (isInboxFolder(folder) ? inboxStamp() : "\u672A\u547D\u540D"));
    let filename = base;
    let n = 2;
    while (this.app.vault.getAbstractFileByPath(folder + "/" + filename + ".md")) {
      filename = base + " " + n++;
    }
    try {
      const file = await this.app.vault.create(folder + "/" + filename + ".md", "");
      await this.openNote(file);
    } catch (e) {
      new import_obsidian.Notice("\u6CA1\u5199\u6210\u3002");
    }
  }
  async newNote(folder) {
    if (!folder)
      return;
    if (!this.app.vault.getAbstractFileByPath(folder)) {
      new import_obsidian.Notice("\u6587\u4EF6\u5939\u4E0D\u5728\u3002");
      return;
    }
    const preset = isInboxFolder(folder) ? inboxStamp() : "";
    new NameModal(this.app, preset, (raw) => {
      void this.createNamedNote(folder, raw);
    }).open();
  }
  card(parent, spec, onClick) {
    const el = parent.createEl("button", {
      cls: "desk-card" + (spec.quiet ? " is-quiet" : "") + (spec.note ? " is-note" : "") + (spec.span2 ? " span-2" : "")
    });
    if (spec.kicker)
      el.createEl("span", { cls: "desk-kicker", text: spec.kicker });
    else if (!spec.note)
      el.createEl("span", { cls: "desk-kicker", text: "\xA0" });
    if (spec.count !== void 0 && spec.count !== "" && spec.count !== null) {
      el.createEl("span", { cls: "desk-count", text: String(spec.count) });
    }
    el.createEl("strong", { text: spec.title });
    if (spec.line)
      el.createEl("span", { cls: "desk-line", text: spec.line });
    else if (!spec.note)
      el.createEl("span", { cls: "desk-line", text: "\xA0" });
    if (onClick)
      el.addEventListener("click", onClick);
    else
      el.addClass("is-still");
    return el;
  }
  nav(root, crumbs, folder) {
    const bar = root.createDiv({ cls: "an-tou-nav" });
    const trail = bar.createDiv({ cls: "an-tou-crumbs" });
    crumbs.forEach((c, i) => {
      if (i > 0)
        trail.createSpan({ text: " \xB7 " });
      const b = trail.createEl("button", { text: c.label });
      b.addEventListener("click", c.go);
    });
    if (folder) {
      const add = bar.createEl("button", {
        cls: "an-tou-add",
        text: "+",
        attr: { type: "button", "aria-label": "\u65B0\u7B14\u8BB0" }
      });
      add.addEventListener("click", (e) => {
        e.preventDefault();
        e.stopPropagation();
        void this.newNote(folder);
      });
    }
  }
  async render() {
    const root = this.contentEl;
    root.empty();
    const inner = root.createDiv({ cls: "an-tou-inner" });
    const page = this.current();
    if (page.type === "home")
      await this.renderHome(inner);
    else if (page.type === "group")
      this.renderGroup(inner, page.room);
    else
      await this.renderFolder(inner, page);
  }
  async renderHome(inner) {
    const title = this.plugin.settings.title || "An Tou";
    inner.createEl("h1", { text: title });
    inner.createEl("span", { cls: "an-tou-date", text: todayLabel() });
    const rooms = this.homeRooms();
    if (rooms.length === 0) {
      inner.createEl("p", {
        cls: "an-tou-lede",
        text: "\u8FD8\u6CA1\u6709\u623F\u95F4\u3002\u6253\u5F00\u8BBE\u7F6E\u6DFB\u52A0\u6587\u4EF6\u5939\uFF0C\u6216\u4ECE\u5E93\u6839\u76EE\u5F55\u751F\u6210\u3002"
      });
      return;
    }
    const grid = inner.createDiv({ cls: "an-tou-grid" });
    for (const room of rooms) {
      const n = this.roomCount(room);
      this.card(
        grid,
        {
          kicker: room.kicker,
          count: room.quiet ? void 0 : n,
          title: room.name,
          line: room.line,
          quiet: room.quiet
        },
        () => this.openRoom(room, title)
      );
    }
    inner.createEl("h2", { text: "\u6700\u8FD1" });
    const recentGrid = inner.createDiv({ cls: "an-tou-grid" });
    const live = this.liveFolders();
    const recent = this.app.vault.getMarkdownFiles().filter((f) => live.some((r) => inFolder(f, r.folder))).filter((f) => !skipped(f.path, this.plugin.settings.skipPaths)).filter((f) => f.basename !== "BACKLOG" && !f.basename.startsWith("BACKLOG")).sort((a, b) => b.stat.mtime - a.stat.mtime).slice(0, 3);
    for (const file of recent) {
      let titleText = titleOf(file);
      const line = await firstLine(this.app, file);
      if (!titleText)
        titleText = line || file.basename;
      const hit = live.find((r) => inFolder(file, r.folder));
      this.card(
        recentGrid,
        {
          kicker: (hit == null ? void 0 : hit.kicker) || "Note",
          title: titleText,
          line: titleText === line ? "" : line,
          note: true
        },
        () => {
          void this.openNote(file);
        }
      );
    }
  }
  renderGroup(inner, room) {
    const title = this.plugin.settings.title || "An Tou";
    this.nav(inner, [{ label: "\u2190 " + title, go: () => this.back() }]);
    inner.createEl("h1", { text: room.name });
    if (room.line)
      inner.createEl("p", { cls: "an-tou-lede", text: room.line });
    const grid = inner.createDiv({ cls: "an-tou-grid" });
    for (const child of this.childrenOf(room.id)) {
      const files = child.folder ? this.mdIn(child.folder, child.pinBacklog ? ["BACKLOG"] : []) : [];
      const n = this.roomCount(child);
      this.card(
        grid,
        {
          count: n,
          title: child.name,
          line: child.line || (n === 1 && files[0] ? titleOf(files[0]) : ""),
          quiet: child.quiet || room.quiet
        },
        () => this.openRoom(child, room.name)
      );
    }
  }
  async renderFolder(inner, page) {
    const title = this.plugin.settings.title || "An Tou";
    const goHome = () => {
      this.stack = [{ type: "home" }];
      void this.render();
    };
    const crumbs = [{ label: "\u2190 " + page.parentLabel, go: () => this.back() }];
    if (page.parentLabel !== title)
      crumbs.push({ label: title, go: goHome });
    this.nav(inner, crumbs, page.folder);
    inner.createEl("h1", { text: page.title });
    const all = this.mdIn(page.folder);
    const backlog = all.find((f) => f.basename === "BACKLOG");
    const useBacklog = page.pinBacklog || !!backlog;
    const subs = this.subfolders(page.folder);
    if (useBacklog && backlog) {
      inner.createEl("p", { cls: "an-tou-lede", text: "\u6B63\u672C\u5728 Backlog\u3002" });
      inner.createEl("h2", { text: "\u6B63\u672C" });
      const top = inner.createDiv({ cls: "an-tou-grid" });
      this.card(
        top,
        { kicker: page.kicker, title: "Backlog", line: backlog.basename, span2: true },
        () => {
          void this.openNote(backlog);
        }
      );
    }
    if (subs.length && !useBacklog) {
      const grid2 = inner.createDiv({ cls: "an-tou-grid" });
      for (const folder of subs) {
        const n = this.mdIn(folder.path).length;
        this.card(grid2, { count: n, title: folder.name }, () => {
          this.push({
            type: "folder",
            title: folder.name,
            folder: folder.path,
            kicker: page.kicker,
            parentLabel: page.title
          });
        });
      }
    }
    let notes = all.filter((f) => f.basename !== "BACKLOG" && f.basename !== "BACKLOG-archive").sort((a, b) => b.stat.mtime - a.stat.mtime);
    const cap = useBacklog ? 7 : page.maxNotes || (notes.length > 40 ? 24 : notes.length);
    const rest = Math.max(0, notes.length - cap);
    if (rest)
      notes = notes.slice(0, cap);
    if (useBacklog)
      inner.createEl("h2", { text: "\u6700\u8FD1\u7684\u7EB8\u6761" });
    const grid = inner.createDiv({ cls: "an-tou-grid" });
    for (const file of notes) {
      const line = await firstLine(this.app, file);
      this.card(
        grid,
        { kicker: page.kicker, title: titleOf(file) || line || file.basename, line, note: true },
        () => {
          void this.openNote(file);
        }
      );
    }
    if (rest > 0) {
      this.card(grid, {
        title: "\u5176\u4F59 " + rest + " \u6761",
        line: "\u7528\u5FEB\u901F\u5207\u6362\u641C\u6807\u9898\u3002",
        note: true,
        quiet: true
      });
    }
    if (!notes.length && !subs.length && !backlog) {
      inner.createEl("p", { cls: "an-tou-lede", text: "\u8FD9\u4E00\u683C\u8FD8\u6CA1\u6709\u7B14\u8BB0\u3002" });
    }
  }
};
var AnTouSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  copy() {
    return this.plugin.settings.uiLang === "en" ? COPY.en : COPY.zh;
  }
  display() {
    const { containerEl } = this;
    const t = this.copy();
    const lang = this.plugin.settings.uiLang === "en" ? "en" : "zh";
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName(t.language).setDesc(t.languageDesc).addButton((b) => {
      b.setButtonText(t.chinese).onClick(() => {
        void this.setLang("zh");
      });
      if (lang === "zh")
        b.setCta();
    }).addButton((b) => {
      b.setButtonText(t.english).onClick(() => {
        void this.setLang("en");
      });
      if (lang === "en")
        b.setCta();
    });
    new import_obsidian.Setting(containerEl).setName(t.desk).setHeading();
    new import_obsidian.Setting(containerEl).setName(t.title).setDesc(t.titleDesc).addText(
      (box) => box.setValue(this.plugin.settings.title).onChange((v) => {
        this.plugin.settings.title = v.trim() || "An Tou";
        void this.saveAndRefresh();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.look).setDesc(t.lookDesc).addToggle(
      (box) => box.setValue(this.plugin.settings.applyLook !== false).onChange((v) => {
        this.plugin.settings.applyLook = v;
        this.plugin.applyLook();
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.openOnStart).setDesc(t.openOnStartDesc).addToggle(
      (box) => box.setValue(this.plugin.settings.openOnStart).onChange((v) => {
        this.plugin.settings.openOnStart = v;
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.collapse).setDesc(t.collapseDesc).addToggle(
      (box) => box.setValue(this.plugin.settings.collapseExplorer).onChange((v) => {
        this.plugin.settings.collapseExplorer = v;
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.skip).setDesc(t.skipDesc).addText(
      (box) => box.setValue(this.plugin.settings.skipPaths.join(", ")).onChange((v) => {
        this.plugin.settings.skipPaths = v.split(",").map((s) => s.trim()).filter(Boolean);
        void this.saveAndRefresh();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.rooms).setHeading();
    new import_obsidian.Setting(containerEl).setDesc(t.roomsDesc).addButton(
      (b) => b.setButtonText(t.addRoom).onClick(() => {
        void this.addRoom();
      })
    ).addButton(
      (b) => b.setButtonText(t.fromVault).onClick(() => {
        void this.rebuildRooms();
      })
    );
    for (const room of this.plugin.settings.rooms) {
      this.drawRoom(containerEl, room, t);
    }
  }
  async setLang(uiLang) {
    this.plugin.settings.uiLang = uiLang;
    await this.plugin.saveSettings();
    this.display();
  }
  async saveAndRefresh() {
    await this.plugin.saveSettings();
    this.plugin.refreshDesks();
  }
  async addRoom() {
    const t = this.copy();
    this.plugin.settings.rooms.push({
      id: "room-" + Date.now().toString(36),
      name: t.newRoom,
      kicker: "ROOM"
    });
    await this.saveAndRefresh();
    this.display();
  }
  async rebuildRooms() {
    this.plugin.settings.rooms = this.plugin.scanRooms();
    await this.saveAndRefresh();
    this.display();
    new import_obsidian.Notice(this.copy().fromVaultNotice);
  }
  drawRoom(containerEl, room, t) {
    const wrap = containerEl.createDiv({ cls: "an-tou-room-edit" });
    new import_obsidian.Setting(wrap).setName(room.name || t.newRoom).setDesc(t.roomId + " \xB7 " + room.id).addExtraButton(
      (b) => b.setIcon("trash").setTooltip(t.remove).onClick(() => {
        void this.removeRoom(room.id);
      })
    );
    const grid = wrap.createDiv({ cls: "an-tou-room-grid" });
    this.textField(grid, t.name, t.nameDesc, room.name, (v) => {
      room.name = v;
    });
    this.textField(grid, t.folder, t.folderDesc, room.folder || "", (v) => {
      room.folder = v.trim() || void 0;
    });
    this.textField(grid, t.kicker, t.kickerDesc, room.kicker || "", (v) => {
      room.kicker = v;
    });
    this.textField(grid, t.line, t.lineDesc, room.line || "", (v) => {
      room.line = v;
    });
    this.textField(grid, t.parent, t.parentDesc, room.parent || "", (v) => {
      room.parent = v.trim() || void 0;
    });
    new import_obsidian.Setting(grid).setName(t.quiet).setDesc(t.quietDesc).addToggle(
      (box) => box.setValue(!!room.quiet).onChange((v) => {
        room.quiet = v;
        void this.saveAndRefresh();
      })
    );
  }
  textField(parent, name, desc, value, assign) {
    new import_obsidian.Setting(parent).setName(name).setDesc(desc).addText(
      (box) => box.setValue(value).onChange((v) => {
        assign(v);
        void this.saveAndRefresh();
      })
    );
  }
  async removeRoom(id) {
    this.plugin.settings.rooms = this.plugin.settings.rooms.filter((r) => r.id !== id);
    await this.saveAndRefresh();
    this.display();
  }
};
var AnTouPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    const saved = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, saved != null ? saved : {});
    if (!Array.isArray(this.settings.rooms))
      this.settings.rooms = [];
    if (!Array.isArray(this.settings.skipPaths))
      this.settings.skipPaths = [];
    if (this.settings.uiLang !== "en")
      this.settings.uiLang = "zh";
    this.registerView(VIEW_TYPE, (leaf) => new DeskView(leaf, this));
    this.addCommand({
      id: "open-desk",
      name: "Open desk",
      callback: () => {
        void this.activateView();
      }
    });
    this.addSettingTab(new AnTouSettingTab(this.app, this));
    this.applyLook();
    this.app.workspace.onLayoutReady(async () => {
      if (this.settings.rooms.length === 0) {
        this.settings.rooms = this.scanRooms();
        await this.saveSettings();
      }
      if (this.settings.openOnStart)
        void this.activateView();
    });
  }
  onunload() {
    document.body.removeClass("an-tou-look");
  }
  applyLook() {
    document.body.toggleClass("an-tou-look", this.settings.applyLook !== false);
  }
  scanRooms() {
    const rooms = [];
    const root = this.app.vault.getRoot();
    for (const child of root.children) {
      if (!(child instanceof import_obsidian.TFolder))
        continue;
      if (child.name.startsWith("."))
        continue;
      if (skipped(child.path, this.settings.skipPaths))
        continue;
      rooms.push({
        id: slug(child.name),
        name: child.name,
        folder: child.path,
        kicker: "ROOM"
      });
    }
    return rooms;
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  refreshDesks() {
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE)) {
      const view = leaf.view;
      if (view == null ? void 0 : view.render)
        void view.render();
    }
  }
  async activateView() {
    const { workspace } = this.app;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE);
    for (const extra of leaves.slice(1))
      extra.detach();
    let leaf = workspace.getLeavesOfType(VIEW_TYPE)[0];
    if (!leaf) {
      leaf = workspace.getLeaf(false);
      await leaf.setViewState({ type: VIEW_TYPE, active: true });
    } else {
      workspace.setActiveLeaf(leaf, { focus: true });
    }
    if (this.settings.collapseExplorer && workspace.leftSplit) {
      workspace.leftSplit.collapse();
    }
  }
};
