/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AnTouPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE = "an-tou-desk";
var DEFAULT_TITLE = "\u683C\u7269\u6210\u6816";
var RECENT_CAP = 3;
var DEFAULT_SETTINGS = {
  title: DEFAULT_TITLE,
  openOnStart: true,
  collapseExplorer: true,
  applyLook: true,
  skipPaths: ["attachments"],
  skipSeeded: false,
  rooms: [],
  uiLang: "zh"
};
var COPY = {
  zh: {
    language: "\u754C\u9762\u8BED\u8A00",
    languageDesc: "\u53EA\u6539\u8BBE\u7F6E\u9875\u7684\u8BF4\u660E\u3002\u4E66\u684C\u5361\u7247\u4E0A\u7684\u4E2D\u6587\u6807\u9898\u8FD8\u662F\u4F60\u81EA\u5DF1\u586B\u7684\u3002",
    chinese: "\u4E2D\u6587",
    english: "English",
    desk: "\u4E66\u684C",
    title: "\u4E66\u684C\u6807\u9898",
    titleDesc: "\u9996\u9875\u6700\u5927\u90A3\u884C\u5B57\uFF0C\u4E5F\u663E\u793A\u5728\u6807\u7B7E\u4E0A\u3002",
    look: "\u5E94\u7528 Quiet Glass \u5916\u89C2",
    lookDesc: "\u8584\u8377\u7EFF\u5E95\u548C\u886C\u7EBF\u5B57\u3002\u5173\u6389\u5C31\u53EA\u7559\u5361\u7247\u4E66\u684C\uFF0C\u989C\u8272\u4ECD\u7528\u4F60\u73B0\u5728\u7684\u4E3B\u9898\u3002",
    openOnStart: "\u6253\u5F00\u5E93\u65F6\u8FDB\u5165\u4E66\u684C",
    openOnStartDesc: "\u542F\u52A8\u65F6\u6253\u5F00\u4E66\u684C\uFF0C\u800C\u4E0D\u662F\u4E0A\u6B21\u90A3\u7BC7\u7B14\u8BB0\u3002",
    collapse: "\u6536\u8D77\u6587\u4EF6\u5217\u8868",
    collapseDesc: "\u6253\u5F00\u4E66\u684C\u65F6\u628A\u5DE6\u8FB9\u6587\u4EF6\u6811\u6536\u8D77\u6765\u3002",
    skip: "\u8DF3\u8FC7\u8FD9\u4E9B\u8DEF\u5F84",
    skipDesc: "\u7528\u9017\u53F7\u5206\u9694\u3002\u8FD9\u4E9B\u6587\u4EF6\u5939\u4E0D\u4F1A\u51FA\u73B0\u5728\u5361\u7247\u548C\u300C\u6700\u8FD1\u300D\u91CC\u3002",
    rooms: "\u623F\u95F4",
    roomsDesc: "\u4E0B\u9762\u8FD9\u5F20\u56FE\u5C31\u662F\u4E66\u684C\u5361\u7247\uFF0C\u5BF9\u7167\u7740\u586B\u5C31\u884C\u3002",
    addRoom: "\u6DFB\u52A0\u623F\u95F4",
    fromVault: "\u6309\u5E93\u6839\u76EE\u5F55\u751F\u6210",
    fromVaultNotice: "\u5DF2\u6309\u6587\u4EF6\u5939\u66F4\u65B0\u623F\u95F4\u3002\u5DF2\u6709\u540D\u79F0\u3001\u8BF4\u660E\u548C\u5F00\u5173\u6CA1\u52A8\u3002",
    roomId: "\u7F16\u53F7",
    remove: "\u5220\u9664\u8FD9\u4E2A\u623F\u95F4",
    name: "\u540D\u79F0",
    nameDesc: "\u5361\u7247\u6B63\u4E2D\u95F4\u6700\u5927\u7684\u90A3\u884C\u5B57\u3002",
    folder: "\u6587\u4EF6\u5939",
    folderDesc: "\u5E93\u91CC\u7684\u8DEF\u5F84\uFF0C\u6BD4\u5982 00-Inbox\u3002\u6536\u7EB3\u67DC\u8FD9\u79CD\u5206\u7EC4\u8BF7\u7559\u7A7A\u3002",
    kicker: "\u5DE6\u4E0A\u89D2\u5C0F\u5B57",
    kickerDesc: "\u5361\u7247\u5DE6\u4E0A\u89D2\u90A3\u4E00\u884C\uFF0C\u6BD4\u5982 Inbox\u3002",
    line: "\u5E95\u4E0B\u90A3\u884C\u8BF4\u660E",
    lineDesc: "\u6807\u9898\u4E0B\u9762\u90A3\u53E5\uFF0C\u5199\u8FD9\u683C\u662F\u5E72\u4EC0\u4E48\u7684\u3002",
    parent: "\u653E\u8FDB\u54EA\u4E2A\u623F\u95F4",
    parentDesc: "\u8981\u51FA\u73B0\u5728\u9996\u9875\u5C31\u7559\u7A7A\u3002\u8981\u6536\u8FDB\u53E6\u4E00\u5F20\u5361\u91CC\uFF0C\u586B\u4E0A\u4E00\u7EA7\u7684\u7F16\u53F7\uFF0C\u6BD4\u5982 cabinet\u3002",
    quiet: "\u5361\u7247\u53D8\u6DE1",
    quietDesc: "\u6253\u5F00\u540E\u8FD9\u5F20\u5361\u53D8\u6DE1\uFF0C\u91CC\u9762\u7684\u7B14\u8BB0\u4E5F\u4E0D\u8FDB\u300C\u6700\u8FD1\u300D\u3002",
    pinBacklog: "\u8FDB\u623F\u95F4\u5148\u770B BACKLOG",
    pinBacklogDesc: "\u6CA1\u6709 BACKLOG.md \u65F6\u4E5F\u53EF\u4EE5\u5F3A\u5236\uFF1A\u5176\u5B83\u7B14\u8BB0\u53EA\u7559\u51E0\u5F20\u6700\u8FD1\u7684\u3002",
    backlogNote: "\u8FD9\u4E2A\u623F\u95F4\u6709 BACKLOG.md",
    backlogNoteDesc: "\u8FDB\u623F\u95F4\u4F1A\u5148\u770B\u5230\u5B83\uFF0C\u5176\u5B83\u7B14\u8BB0\u53D8\u6210\u4E0B\u9762\u51E0\u5F20\u6700\u8FD1\u7684\u3002\u653E\u8FDB BACKLOG.md \u5C31\u4F1A\u8FD9\u6837\uFF0C\u4E0D\u7528\u53E6\u5F00\u5F00\u5173\u3002",
    maxNotes: "\u6700\u591A\u663E\u793A\u51E0\u5F20",
    maxNotesDesc: "\u8FD9\u4E2A\u623F\u95F4\u91CC\u6700\u591A\u663E\u793A\u591A\u5C11\u5F20\u7B14\u8BB0\u5361\u7247\u3002\u7559\u7A7A\u5C31\u81EA\u52A8\u51B3\u5B9A\u3002",
    newRoom: "\u65B0\u623F\u95F4",
    saveRoom: "\u4FDD\u5B58",
    draftHint: "\u672A\u4FDD\u5B58\u3002\u586B\u597D\u540E\u70B9\u4FDD\u5B58\uFF0C\u8FD9\u5F20\u5361\u4F1A\u79FB\u5230\u6700\u4E0B\u9762\u3002",
    roleGroup: "\u9996\u9875\u5206\u7EC4\u3002\u6587\u4EF6\u5939\u7A7A\u7740\u6CA1\u95EE\u9898\uFF0C\u5B50\u623F\u95F4\u628A\u300C\u653E\u8FDB\u54EA\u4E2A\u623F\u95F4\u300D\u586B\u6210\u8FD9\u4E2A\u7F16\u53F7\u3002",
    roleHomeFolder: "\u9996\u9875\u5361\u7247\uFF0C\u5BF9\u7740\u4E0B\u9762\u7684\u6587\u4EF6\u5939\u3002",
    roleNested: "\u4E0D\u5728\u9996\u9875\uFF0C\u6536\u5728\u7F16\u53F7 ",
    helpTitle: "\u4E66\u684C\u5361\u7247\u957F\u8FD9\u6837",
    helpKickerCap: "\u5DE6\u4E0A\u89D2\u5C0F\u5B57",
    helpNameCap: "\u540D\u79F0",
    helpLineCap: "\u5E95\u4E0B\u90A3\u884C\u8BF4\u660E",
    helpFolderCap: "\u6587\u4EF6\u5939",
    helpFolderNote: "\u586B 00-Inbox \u8FD9\u7C7B\u8DEF\u5F84\u3002\u7559\u7A7A\u7684\u8BDD\uFF0C\u70B9\u8FDB\u53BB\u770B\u5230\u7684\u662F\u5B50\u623F\u95F4\uFF0C\u4E0D\u662F\u7B14\u8BB0\u3002",
    helpParentCap: "\u653E\u8FDB\u54EA\u4E2A\u623F\u95F4",
    helpParentNote: "\u6536\u7EB3\u67DC\u7684\u7F16\u53F7\u662F cabinet\u3002\u4E2A\u4EBA\u601D\u8003\u8981\u85CF\u8FDB\u67DC\u5B50\uFF0C\u8FD9\u91CC\u586B cabinet\uFF0C\u9996\u9875\u5C31\u53EA\u5269\u6536\u7EB3\u67DC\u3002",
    helpQuietCap: "\u5361\u7247\u53D8\u6DE1",
    helpQuietNote: "\u6253\u5F00\u540E\u8FD9\u5F20\u5361\u53D8\u6DE1\uFF0C\u91CC\u9762\u7684\u7B14\u8BB0\u4E5F\u4E0D\u51FA\u73B0\u5728\u300C\u6700\u8FD1\u300D\u3002",
    helpCountCap: "\u6570\u91CF\uFF0C\u4E0D\u7528\u586B",
    helpHome: "\u9996\u9875",
    helpInside: "\u70B9\u8FDB\u6536\u7EB3\u67DC\u4E4B\u540E"
  },
  en: {
    language: "Language",
    languageDesc: "Settings copy only. Card titles stay whatever you typed.",
    chinese: "\u4E2D\u6587",
    english: "English",
    desk: "Desk",
    title: "Desk title",
    titleDesc: "The large heading on the home cards and the tab.",
    look: "Apply Quiet Glass look",
    lookDesc: "Mint paper and serif type. Off keeps the cards and your current theme.",
    openOnStart: "Open on start",
    openOnStartDesc: "Show the desk when the vault opens, instead of the last note.",
    collapse: "Collapse file explorer",
    collapseDesc: "Fold the left file tree when the desk opens.",
    skip: "Skip these paths",
    skipDesc: "Comma-separated folder prefixes hidden from cards and recents.",
    rooms: "Rooms",
    roomsDesc: "The picture below is a desk card. Fill the fields to match.",
    addRoom: "Add room",
    fromVault: "Build from top-level folders",
    fromVaultNotice: "Rooms updated from folders. Names, captions, and toggles were kept.",
    roomId: "Id",
    remove: "Remove this room",
    name: "Name",
    nameDesc: "The large title in the middle of the card.",
    folder: "Folder",
    folderDesc: "A vault path such as 00-Inbox. Leave empty for a group like Cabinet.",
    kicker: "Top-left text",
    kickerDesc: "The small line at the top-left, such as Inbox.",
    line: "Caption under the title",
    lineDesc: "The sentence under the title, what this room is for.",
    parent: "Put inside this room",
    parentDesc: "Leave empty to stay on the home grid. To nest it, type the parent id, such as cabinet.",
    quiet: "Fade the card",
    quietDesc: "The card fades, and its notes stay out of recents.",
    pinBacklog: "Show BACKLOG first",
    pinBacklogDesc: "Force the same layout without a BACKLOG.md: other notes stay as a few recent slips.",
    backlogNote: "This room has BACKLOG.md",
    backlogNoteDesc: "Opening the room shows it first; other notes become a few recent slips. Automatic when that file exists.",
    maxNotes: "Max notes shown",
    maxNotesDesc: "How many note cards this room shows at most. Empty means automatic.",
    newRoom: "New room",
    saveRoom: "Save",
    draftHint: "Unsaved. Fill it in, then save, and it moves to the bottom.",
    roleGroup: "Home group. Empty folder is fine; children type this id in Put inside this room.",
    roleHomeFolder: "Home card, pointed at the folder below.",
    roleNested: "Not on home. Nested under ",
    helpTitle: "A desk card looks like this",
    helpKickerCap: "Top-left text",
    helpNameCap: "Name",
    helpLineCap: "Caption under the title",
    helpFolderCap: "Folder",
    helpFolderNote: "A path like 00-Inbox. Leave empty and this card is only a group.",
    helpParentCap: "Put inside this room",
    helpParentNote: "Cabinet's id is cabinet. A child that should live there types cabinet, and leaves the home grid.",
    helpQuietCap: "Fade the card",
    helpQuietNote: "The card fades, and its notes stay out of recents.",
    helpCountCap: "Count, automatic",
    helpHome: "Home",
    helpInside: "After you open Cabinet"
  }
};
function slug(name) {
  const s = name.toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]+/g, "-").replace(/^-|-$/g, "");
  return s || "room-" + Date.now().toString(36);
}
function uniqueId(base, used) {
  const root = base || "room";
  if (!used.has(root)) {
    used.add(root);
    return root;
  }
  let n = 2;
  while (used.has(root + "-" + n))
    n++;
  const id = root + "-" + n;
  used.add(id);
  return id;
}
function kickerOf(folderName) {
  let s = folderName.replace(/^\d+[-_\s]*/, "").trim();
  s = s.replace(/（[^）]*）/g, "").replace(/\([^)]*\)/g, "").trim();
  if (!s)
    s = folderName.replace(/^\d+[-_\s]*/, "").trim() || folderName;
  if (/[\u4e00-\u9fff]/.test(s)) {
    s = s.replace(/^[A-Za-z0-9]+[-_]/, "").trim() || s;
    return s.slice(0, 4);
  }
  if (/^[A-Za-z0-9][A-Za-z0-9._ -]*$/.test(s)) {
    const parts = s.split(/[-_\s]+/).filter(Boolean);
    if (parts.length === 1) {
      const w = parts[0];
      return w.length <= 12 ? w : w.slice(0, 8);
    }
    const first = parts[0];
    if (first.length >= 3 && first.length <= 10)
      return first;
    return parts.map((p) => p[0]).join("").slice(0, 8);
  }
  return s.slice(0, 4);
}
function noteCountLine(n, zh) {
  if (n <= 0)
    return void 0;
  return zh ? n + " \u7BC7\u7B14\u8BB0" : n + " notes";
}
function isAutoLine(line) {
  if (!line)
    return false;
  const s = line.trim();
  return /^\d+\s*篇笔记$/.test(s) || /^\d+\s*notes?$/i.test(s);
}
function isAutoKicker(room) {
  if (!room.kicker || !room.folder)
    return false;
  const base = room.folder.slice(room.folder.lastIndexOf("/") + 1);
  return room.kicker === kickerOf(base);
}
function inFolder(file, folder) {
  if (!folder)
    return false;
  return file.path === folder + ".md" || file.path.startsWith(folder + "/");
}
function skipped(path, skipPaths) {
  return skipPaths.some((s) => path === s || path.startsWith(s + "/"));
}
function weakBasename(file) {
  return /^\d{4}-\d{2}-\d{2}\b/.test(file.basename) || /quick$/i.test(file.basename);
}
function titleOf(file) {
  if (weakBasename(file))
    return "";
  if (file.basename === "BACKLOG")
    return "Backlog";
  return file.basename;
}
function frontmatterTitle(app, file) {
  var _a, _b;
  const raw = (_b = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter) == null ? void 0 : _b.title;
  if (typeof raw === "string" && raw.trim())
    return raw.trim();
  if (Array.isArray(raw) && raw.length && String(raw[0]).trim())
    return String(raw[0]).trim();
  return "";
}
function firstH1(app, file, body) {
  var _a, _b, _c;
  const heading = (_b = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.headings) == null ? void 0 : _b.find((h) => h.level === 1);
  if ((_c = heading == null ? void 0 : heading.heading) == null ? void 0 : _c.trim())
    return heading.heading.trim();
  for (const raw of body.split("\n")) {
    const m = raw.trim().match(/^#\s+(.+)$/);
    if (m)
      return m[1].replace(/\s+#+\s*$/, "").trim();
  }
  return "";
}
function firstReadableFrom(body) {
  for (const raw of body.split("\n")) {
    let ln = raw.trim();
    if (!ln)
      continue;
    if (ln === "---" || ln === "***" || ln === "___")
      continue;
    if (ln.startsWith("```") || ln.startsWith("`"))
      continue;
    if (ln.startsWith("#"))
      continue;
    if (ln.startsWith("!"))
      continue;
    if (ln.startsWith(">"))
      continue;
    ln = ln.replace(/^[-*+]\s+\[[ xX]\]\s*/, "").replace(/^[-*+]\s+/, "").replace(/^\d+\.\s+/, "").replace(/\[([^\]]+)\]\([^)]*\)/g, "$1").replace(/\[\[([^\]|]+)(\|[^\]]*)?\]\]/g, (_m, p1, p2) => p2 ? String(p2).slice(1) : p1).replace(/`[^`]+`/g, "").replace(/[*_]/g, "").replace(/\s+/g, " ").trim();
    if (ln.length < 2)
      continue;
    return ln.slice(0, 48);
  }
  return "";
}
function stripFrontmatter(app, file, text) {
  var _a, _b, _c;
  const offset = (_c = (_b = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatterPosition) == null ? void 0 : _b.end) == null ? void 0 : _c.offset;
  if (typeof offset === "number" && offset > 0 && offset <= text.length) {
    return text.slice(offset);
  }
  if (!text.startsWith("---"))
    return text;
  const end = text.indexOf("\n---", 3);
  if (end === -1)
    return text;
  return text.slice(end + 4);
}
async function noteCardCopy(app, file) {
  if (file.basename === "BACKLOG")
    return { title: "Backlog", line: "" };
  let body = "";
  try {
    body = stripFrontmatter(app, file, await app.vault.cachedRead(file));
  } catch (e) {
  }
  const yaml = frontmatterTitle(app, file);
  const h1 = firstH1(app, file, body);
  const sentence = firstReadableFrom(body);
  const base = file.basename;
  const title = yaml || h1 || sentence || (weakBasename(file) ? "" : titleOf(file)) || base;
  const line = sentence && sentence !== title ? sentence : "";
  return { title, line };
}
function todayLabel() {
  const lang = document.documentElement.lang || navigator.language || "zh-CN";
  const tag = lang.toLowerCase().startsWith("zh") ? "zh-CN" : lang;
  return new Date().toLocaleDateString(tag, { month: "long", day: "numeric" });
}
function twoDigits(n) {
  return (n < 10 ? "0" : "") + String(n);
}
function inboxStamp() {
  const d = new Date();
  return `${d.getFullYear()}-${twoDigits(d.getMonth() + 1)}-${twoDigits(d.getDate())} ${twoDigits(d.getHours())}${twoDigits(d.getMinutes())}`;
}
function safeName(name) {
  return name.replace(/[\\/:*?"<>|]/g, "").replace(/\s+/g, " ").trim() || "\u672A\u547D\u540D";
}
function isInboxFolder(folder) {
  return /inbox/i.test(folder);
}
var NameModal = class extends import_obsidian.Modal {
  constructor(app, preset, onSubmit) {
    super(app);
    this.preset = preset || "";
    this.onSubmit = onSubmit;
  }
  onOpen() {
    this.titleEl.setText("\u65B0\u7B14\u8BB0");
    const input = this.contentEl.createEl("input", { type: "text", cls: "prompt-input" });
    input.value = this.preset;
    input.placeholder = "\u8FD9\u7BC7\u53EB\u4EC0\u4E48";
    input.addEventListener("keydown", (e) => {
      if (e.key !== "Enter")
        return;
      e.preventDefault();
      const v = input.value.trim();
      this.close();
      this.onSubmit(v);
    });
    input.focus();
    if (this.preset)
      input.select();
  }
};
var DeskView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.stack = [{ type: "home" }];
    this._tid = 0;
    this.renderSeq = 0;
    this.dirty = false;
    this.renderFiles = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return this.plugin.settings.title || DEFAULT_TITLE;
  }
  getIcon() {
    return "layout-grid";
  }
  async onOpen() {
    this.contentEl.addClass("an-tou-view");
    this.registerEvent(this.app.vault.on("create", () => this.safeRender()));
    this.registerEvent(this.app.vault.on("delete", () => this.safeRender()));
    this.registerEvent(this.app.vault.on("rename", () => this.safeRender()));
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (this.modifyAffectsPage(file))
          this.safeRender();
      })
    );
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        if (this.dirty && this.isShownNow()) {
          this.dirty = false;
          void this.render();
        }
      })
    );
    await this.render();
  }
  async onClose() {
    if (this._tid)
      window.clearTimeout(this._tid);
    this.renderSeq++;
    this.contentEl.empty();
  }
  isShownNow() {
    if (typeof this.contentEl.isShown === "function")
      return this.contentEl.isShown();
    return this.contentEl.offsetParent !== null;
  }
  modifyAffectsPage(file) {
    if (!(file instanceof import_obsidian.TFile))
      return true;
    const page = this.current();
    if (page.type === "folder" || page.type === "more") {
      return inFolder(file, page.folder);
    }
    if (page.type === "home") {
      return !!this.ownerOf(file, this.liveFolders());
    }
    return true;
  }
  safeRender() {
    if (!this.isShownNow()) {
      this.dirty = true;
      if (this._tid) {
        window.clearTimeout(this._tid);
        this._tid = 0;
      }
      return;
    }
    if (this._tid)
      window.clearTimeout(this._tid);
    this._tid = window.setTimeout(() => {
      this._tid = 0;
      void this.render();
    }, 200);
  }
  resetHome() {
    this.stack = [{ type: "home" }];
    return this.render();
  }
  current() {
    return this.stack[this.stack.length - 1];
  }
  push(page) {
    this.stack.push(page);
    void this.render();
  }
  back() {
    if (this.stack.length > 1) {
      this.stack.pop();
      void this.render();
    }
  }
  mdIn(folder, extraSkip = []) {
    var _a;
    if (!folder)
      return [];
    const skip = this.plugin.settings.skipPaths;
    const all = (_a = this.renderFiles) != null ? _a : this.app.vault.getMarkdownFiles();
    return all.filter((f) => {
      if (!inFolder(f, folder))
        return false;
      if (skipped(f.path, skip))
        return false;
      return !extraSkip.some((s) => f.path.endsWith(s) || f.basename === s);
    });
  }
  subfolders(folder) {
    const af = this.app.vault.getAbstractFileByPath(folder);
    if (!(af instanceof import_obsidian.TFolder))
      return [];
    const skip = this.plugin.settings.skipPaths;
    return af.children.filter((c) => {
      if (!(c instanceof import_obsidian.TFolder))
        return false;
      if (c.name.startsWith("."))
        return false;
      return !skipped(c.path, skip);
    });
  }
  homeRooms() {
    return this.plugin.settings.rooms.filter((r) => !r.parent && !r.draft);
  }
  childrenOf(id) {
    return this.plugin.settings.rooms.filter(
      (r) => r.parent === id && r.id !== id && !r.draft
    );
  }
  isQuietLine(room, seen) {
    if (room.quiet)
      return true;
    if (!room.parent)
      return false;
    const visited = seen != null ? seen : /* @__PURE__ */ new Set();
    visited.add(room.id);
    if (visited.has(room.parent))
      return false;
    const parent = this.plugin.settings.rooms.find((r) => r.id === room.parent);
    return parent ? this.isQuietLine(parent, visited) : false;
  }
  liveFolders() {
    const out = [];
    for (const room of this.plugin.settings.rooms) {
      if (room.draft)
        continue;
      if (this.isQuietLine(room))
        continue;
      if (!room.folder)
        continue;
      out.push({
        id: room.id,
        folder: room.folder,
        kicker: room.kicker || room.name
      });
    }
    return out;
  }
  ownerOf(file, live) {
    let best;
    for (const room of live) {
      if (!inFolder(file, room.folder))
        continue;
      if (!best || room.folder.length > best.folder.length)
        best = room;
    }
    return best;
  }
  roomCount(room) {
    const kids = this.childrenOf(room.id);
    if (kids.length)
      return kids.length;
    if (room.folder)
      return this.mdIn(room.folder).length;
    return 0;
  }
  openRoom(room, parentLabel) {
    const kids = this.childrenOf(room.id);
    if (kids.length) {
      this.push({ type: "group", room });
      return;
    }
    if (room.folder) {
      this.push({
        type: "folder",
        title: room.name,
        folder: room.folder,
        kicker: room.kicker || room.name,
        parentLabel,
        pinBacklog: room.pinBacklog,
        maxNotes: room.maxNotes
      });
    }
  }
  async openNote(file) {
    await this.app.workspace.getLeaf("tab").openFile(file);
  }
  async createNamedNote(folder, raw) {
    const base = safeName(raw || (isInboxFolder(folder) ? inboxStamp() : "\u672A\u547D\u540D"));
    let filename = base;
    let n = 2;
    while (this.app.vault.getAbstractFileByPath(folder + "/" + filename + ".md")) {
      filename = base + " " + n++;
    }
    try {
      const file = await this.app.vault.create(folder + "/" + filename + ".md", "");
      await this.openNote(file);
    } catch (e) {
      new import_obsidian.Notice("\u6CA1\u5199\u6210\u3002");
    }
  }
  async newNote(folder) {
    if (!folder)
      return;
    if (!this.app.vault.getAbstractFileByPath(folder)) {
      new import_obsidian.Notice("\u6587\u4EF6\u5939\u4E0D\u5728\u3002");
      return;
    }
    const preset = isInboxFolder(folder) ? inboxStamp() : "";
    new NameModal(this.app, preset, (raw) => {
      void this.createNamedNote(folder, raw);
    }).open();
  }
  card(parent, spec, onClick) {
    const el = parent.createEl("button", {
      cls: "desk-card" + (spec.quiet ? " is-quiet" : "") + (spec.note ? " is-note" : "") + (spec.span2 ? " span-2" : "")
    });
    if (spec.kicker)
      el.createEl("span", { cls: "desk-kicker", text: spec.kicker });
    else if (!spec.note)
      el.createEl("span", { cls: "desk-kicker", text: "\xA0" });
    if (spec.count !== void 0 && spec.count !== "" && spec.count !== null) {
      el.createEl("span", { cls: "desk-count", text: String(spec.count) });
    }
    el.createEl("strong", { text: spec.title });
    if (spec.line)
      el.createEl("span", { cls: "desk-line", text: spec.line });
    else if (!spec.note)
      el.createEl("span", { cls: "desk-line", text: "\xA0" });
    if (onClick)
      el.addEventListener("click", onClick);
    else
      el.addClass("is-still");
    return el;
  }
  nav(root, crumbs, folder) {
    const bar = root.createDiv({ cls: "an-tou-nav" });
    const trail = bar.createDiv({ cls: "an-tou-crumbs" });
    crumbs.forEach((c, i) => {
      if (i > 0)
        trail.createSpan({ text: " \xB7 " });
      const b = trail.createEl("button", { text: c.label });
      b.addEventListener("click", c.go);
    });
    if (folder) {
      const add = bar.createEl("button", {
        cls: "an-tou-add",
        text: "+",
        attr: { type: "button", "aria-label": "\u65B0\u7B14\u8BB0" }
      });
      add.addEventListener("click", (e) => {
        e.preventDefault();
        e.stopPropagation();
        void this.newNote(folder);
      });
    }
  }
  async render() {
    const seq = ++this.renderSeq;
    this.renderFiles = this.app.vault.getMarkdownFiles();
    try {
      const root = this.contentEl;
      root.empty();
      const inner = root.createDiv({ cls: "an-tou-inner" });
      const page = this.current();
      if (page.type === "home")
        await this.renderHome(inner, seq);
      else if (page.type === "group")
        this.renderGroup(inner, page.room);
      else if (page.type === "more")
        await this.renderMore(inner, page, seq);
      else
        await this.renderFolder(inner, page, seq);
    } finally {
      if (this.renderSeq === seq)
        this.renderFiles = null;
    }
  }
  async renderHome(inner, seq) {
    const title = this.plugin.settings.title || DEFAULT_TITLE;
    inner.createEl("h1", { text: title });
    inner.createEl("span", { cls: "an-tou-date", text: todayLabel() });
    const rooms = this.homeRooms();
    if (rooms.length === 0) {
      inner.createEl("p", {
        cls: "an-tou-lede",
        text: "\u8FD8\u6CA1\u6709\u623F\u95F4\u3002\u6253\u5F00\u8BBE\u7F6E\u6DFB\u52A0\u6587\u4EF6\u5939\uFF0C\u6216\u4ECE\u5E93\u6839\u76EE\u5F55\u751F\u6210\u3002"
      });
      return;
    }
    const grid = inner.createDiv({ cls: "an-tou-grid" });
    for (const room of rooms) {
      const n = this.roomCount(room);
      this.card(
        grid,
        {
          kicker: room.kicker,
          count: room.quiet ? void 0 : n,
          title: room.name,
          line: room.line,
          quiet: room.quiet
        },
        () => this.openRoom(room, title)
      );
    }
    inner.createEl("h2", { text: "\u6700\u8FD1" });
    const recentGrid = inner.createDiv({ cls: "an-tou-grid" });
    const recent = this.recentNotes();
    for (const entry of recent) {
      const file = entry.file;
      const copy = await noteCardCopy(this.app, file);
      if (seq !== this.renderSeq)
        return;
      this.card(
        recentGrid,
        {
          kicker: entry.owner.kicker || "Note",
          title: copy.title,
          line: copy.line,
          note: true
        },
        () => {
          void this.openNote(file);
        }
      );
    }
  }
  recentNotes() {
    var _a;
    const live = this.liveFolders();
    const skip = this.plugin.settings.skipPaths;
    const all = (_a = this.renderFiles) != null ? _a : this.app.vault.getMarkdownFiles();
    const owned = [];
    for (const file of all) {
      if (skipped(file.path, skip))
        continue;
      if (file.basename === "BACKLOG" || file.basename.startsWith("BACKLOG"))
        continue;
      const owner = this.ownerOf(file, live);
      if (!owner)
        continue;
      owned.push({ file, owner });
    }
    const buckets = /* @__PURE__ */ new Map();
    for (const entry of owned) {
      const list = buckets.get(entry.owner.id) || [];
      list.push(entry);
      buckets.set(entry.owner.id, list);
    }
    for (const list of buckets.values()) {
      list.sort((a, b) => b.file.stat.mtime - a.file.stat.mtime);
    }
    const rooms = Array.from(buckets.values()).filter((list) => list.length).sort((a, b) => b[0].file.stat.mtime - a[0].file.stat.mtime);
    const picked = [];
    const seen = /* @__PURE__ */ new Set();
    for (const list of rooms) {
      if (picked.length >= RECENT_CAP)
        break;
      picked.push(list[0]);
      seen.add(list[0].file.path);
    }
    if (picked.length < RECENT_CAP) {
      const rest = owned.filter((e) => !seen.has(e.file.path)).sort((a, b) => b.file.stat.mtime - a.file.stat.mtime);
      for (const entry of rest) {
        if (picked.length >= RECENT_CAP)
          break;
        picked.push(entry);
      }
    }
    return picked;
  }
  renderGroup(inner, room) {
    const title = this.plugin.settings.title || DEFAULT_TITLE;
    this.nav(inner, [{ label: "\u2190 " + title, go: () => this.back() }]);
    inner.createEl("h1", { text: room.name });
    if (room.line)
      inner.createEl("p", { cls: "an-tou-lede", text: room.line });
    const grid = inner.createDiv({ cls: "an-tou-grid" });
    for (const child of this.childrenOf(room.id)) {
      const files = child.folder ? this.mdIn(child.folder, child.pinBacklog ? ["BACKLOG"] : []) : [];
      const n = this.roomCount(child);
      this.card(
        grid,
        {
          count: n,
          title: child.name,
          line: child.line || (n === 1 && files[0] ? titleOf(files[0]) : ""),
          quiet: this.isQuietLine(child)
        },
        () => this.openRoom(child, room.name)
      );
    }
  }
  async renderFolder(inner, page, seq) {
    const title = this.plugin.settings.title || DEFAULT_TITLE;
    const goHome = () => {
      this.stack = [{ type: "home" }];
      void this.render();
    };
    const crumbs = [{ label: "\u2190 " + page.parentLabel, go: () => this.back() }];
    if (page.parentLabel !== title)
      crumbs.push({ label: title, go: goHome });
    this.nav(inner, crumbs, page.folder);
    inner.createEl("h1", { text: page.title });
    const all = this.mdIn(page.folder);
    const backlog = all.find((f) => f.basename === "BACKLOG");
    const useBacklog = page.pinBacklog || !!backlog;
    const subs = this.subfolders(page.folder);
    if (useBacklog && backlog) {
      inner.createEl("p", { cls: "an-tou-lede", text: "\u6B63\u672C\u5728 Backlog\u3002" });
      inner.createEl("h2", { text: "\u6B63\u672C" });
      const top = inner.createDiv({ cls: "an-tou-grid" });
      this.card(
        top,
        { kicker: page.kicker, title: "Backlog", line: backlog.basename, span2: true },
        () => {
          void this.openNote(backlog);
        }
      );
    }
    if (subs.length && !useBacklog) {
      const grid2 = inner.createDiv({ cls: "an-tou-grid" });
      for (const folder of subs) {
        const n = this.mdIn(folder.path).length;
        this.card(grid2, { count: n, title: folder.name }, () => {
          this.push({
            type: "folder",
            title: folder.name,
            folder: folder.path,
            kicker: page.kicker,
            parentLabel: page.title
          });
        });
      }
    }
    let notes = all.filter((f) => f.basename !== "BACKLOG" && f.basename !== "BACKLOG-archive").sort((a, b) => b.stat.mtime - a.stat.mtime);
    const cap = page.maxNotes || (useBacklog ? 7 : notes.length > 40 ? 24 : notes.length);
    const rest = Math.max(0, notes.length - cap);
    if (rest)
      notes = notes.slice(0, cap);
    if (useBacklog)
      inner.createEl("h2", { text: "\u6700\u8FD1\u7684\u7EB8\u6761" });
    const grid = inner.createDiv({ cls: "an-tou-grid" });
    for (const file of notes) {
      const copy = await noteCardCopy(this.app, file);
      if (seq !== this.renderSeq)
        return;
      this.card(
        grid,
        { kicker: page.kicker, title: copy.title, line: copy.line, note: true },
        () => {
          void this.openNote(file);
        }
      );
    }
    if (rest > 0) {
      this.card(
        grid,
        {
          title: "\u5176\u4F59 " + rest + " \u6761",
          note: true,
          quiet: true
        },
        () => {
          this.push({
            type: "more",
            title: page.title,
            folder: page.folder,
            kicker: page.kicker,
            parentLabel: page.parentLabel,
            pinBacklog: page.pinBacklog,
            maxNotes: page.maxNotes,
            skip: cap
          });
        }
      );
    }
    if (!notes.length && !subs.length && !backlog) {
      inner.createEl("p", { cls: "an-tou-lede", text: "\u8FD9\u4E00\u683C\u8FD8\u6CA1\u6709\u7B14\u8BB0\u3002" });
    }
  }
  async renderMore(inner, page, seq) {
    this.nav(
      inner,
      [{ label: "\u2190 " + page.title, go: () => this.back() }],
      page.folder
    );
    inner.createEl("h1", { text: page.title });
    const notes = this.mdIn(page.folder).filter((f) => f.basename !== "BACKLOG" && f.basename !== "BACKLOG-archive").sort((a, b) => b.stat.mtime - a.stat.mtime).slice(page.skip);
    inner.createEl("p", {
      cls: "an-tou-lede",
      text: notes.length ? "\u5176\u4F59 " + notes.length + " \u6761" : "\u6CA1\u6709\u66F4\u591A\u7B14\u8BB0\u3002"
    });
    const grid = inner.createDiv({ cls: "an-tou-grid" });
    for (const file of notes) {
      const copy = await noteCardCopy(this.app, file);
      if (seq !== this.renderSeq)
        return;
      this.card(
        grid,
        { kicker: page.kicker, title: copy.title, line: copy.line, note: true },
        () => {
          void this.openNote(file);
        }
      );
    }
  }
};
var AnTouSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this._saveTimer = null;
    this._savePending = false;
    this.plugin = plugin;
  }
  copy() {
    return this.plugin.settings.uiLang === "en" ? COPY.en : COPY.zh;
  }
  display() {
    const { containerEl } = this;
    const t = this.copy();
    const lang = this.plugin.settings.uiLang === "en" ? "en" : "zh";
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName(t.language).setDesc(t.languageDesc).addButton((b) => {
      b.setButtonText(t.chinese).onClick(() => {
        void this.setLang("zh");
      });
      if (lang === "zh")
        b.setCta();
    }).addButton((b) => {
      b.setButtonText(t.english).onClick(() => {
        void this.setLang("en");
      });
      if (lang === "en")
        b.setCta();
    });
    new import_obsidian.Setting(containerEl).setName(t.desk).setHeading();
    new import_obsidian.Setting(containerEl).setName(t.title).setDesc(t.titleDesc).addText(
      (box) => box.setValue(this.plugin.settings.title).onChange((v) => {
        this.plugin.settings.title = v.trim() || DEFAULT_TITLE;
        this.debouncedSave();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.look).setDesc(t.lookDesc).addToggle(
      (box) => box.setValue(this.plugin.settings.applyLook !== false).onChange((v) => {
        this.plugin.settings.applyLook = v;
        this.plugin.applyLook();
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.openOnStart).setDesc(t.openOnStartDesc).addToggle(
      (box) => box.setValue(this.plugin.settings.openOnStart).onChange((v) => {
        this.plugin.settings.openOnStart = v;
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.collapse).setDesc(t.collapseDesc).addToggle(
      (box) => box.setValue(this.plugin.settings.collapseExplorer).onChange((v) => {
        this.plugin.settings.collapseExplorer = v;
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.skip).setDesc(t.skipDesc).addText(
      (box) => box.setValue(this.plugin.settings.skipPaths.join(", ")).onChange((v) => {
        this.plugin.settings.skipPaths = v.split(",").map((s) => s.trim()).filter(Boolean);
        this.debouncedSave();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t.rooms).setHeading();
    this.fillHelp(containerEl.createDiv({ cls: "an-tou-help-inline" }), t);
    new import_obsidian.Setting(containerEl).setDesc(t.roomsDesc).addButton(
      (b) => b.setButtonText(t.addRoom).onClick(() => {
        void this.addRoom();
      })
    ).addButton(
      (b) => b.setButtonText(t.fromVault).onClick(() => {
        void this.rebuildRooms();
      })
    );
    const drafts = this.plugin.settings.rooms.filter((r) => r.draft);
    const rest = this.plugin.settings.rooms.filter((r) => !r.draft);
    for (const room of drafts.concat(rest)) {
      this.drawRoom(containerEl, room, t);
    }
  }
  async setLang(uiLang) {
    this.plugin.settings.uiLang = uiLang;
    await this.plugin.saveSettings();
    this.display();
  }
  async saveAndRefresh() {
    if (this._saveTimer !== null) {
      window.clearTimeout(this._saveTimer);
      this._saveTimer = null;
    }
    this._savePending = false;
    await this.plugin.saveSettings();
    this.plugin.refreshDesks();
  }
  debouncedSave() {
    this._savePending = true;
    if (this._saveTimer !== null)
      window.clearTimeout(this._saveTimer);
    this._saveTimer = window.setTimeout(() => {
      void this.saveAndRefresh();
    }, 400);
  }
  hide() {
    const pending = this._savePending;
    if (this._saveTimer !== null) {
      window.clearTimeout(this._saveTimer);
      this._saveTimer = null;
    }
    this._savePending = false;
    if (pending)
      void this.saveAndRefresh();
  }
  async addRoom() {
    const t = this.copy();
    this.plugin.settings.rooms.unshift({
      id: "room-" + Date.now().toString(36),
      name: t.newRoom,
      draft: true
    });
    await this.saveAndRefresh();
    this.display();
  }
  async saveRoom(id) {
    const rooms = this.plugin.settings.rooms;
    const i = rooms.findIndex((r) => r.id === id);
    if (i < 0)
      return;
    const [room] = rooms.splice(i, 1);
    delete room.draft;
    rooms.push(room);
    await this.saveAndRefresh();
    this.display();
  }
  async rebuildRooms() {
    this.plugin.settings.rooms = this.plugin.mergeRooms(this.plugin.scanRooms());
    await this.saveAndRefresh();
    this.display();
    new import_obsidian.Notice(this.copy().fromVaultNotice);
  }
  drawRoom(containerEl, room, t) {
    const wrap = containerEl.createDiv({
      cls: "an-tou-room-edit" + (room.draft ? " is-draft" : "")
    });
    const head = new import_obsidian.Setting(wrap).setName(room.name || t.newRoom).setDesc(t.roomId + " \xB7 " + room.id + "\n" + this.roomRole(room, t));
    if (room.draft) {
      head.addButton(
        (b) => b.setButtonText(t.saveRoom).setCta().onClick(() => {
          void this.saveRoom(room.id);
        })
      );
    }
    head.addExtraButton(
      (b) => b.setIcon("trash").setTooltip(t.remove).onClick(() => {
        void this.removeRoom(room.id);
      })
    );
    const grid = wrap.createDiv({ cls: "an-tou-room-grid" });
    this.textField(grid, t.name, t.nameDesc, room.name, (v) => {
      room.name = v;
    });
    this.textField(grid, t.folder, t.folderDesc, room.folder || "", (v) => {
      room.folder = v.trim() || void 0;
    });
    this.textField(grid, t.kicker, t.kickerDesc, room.kicker || "", (v) => {
      room.kicker = v;
    });
    this.textField(grid, t.line, t.lineDesc, room.line || "", (v) => {
      room.line = v;
    });
    this.textField(grid, t.parent, t.parentDesc, room.parent || "", (v) => {
      room.parent = v.trim() || void 0;
    });
    this.textField(
      grid,
      t.maxNotes,
      t.maxNotesDesc,
      room.maxNotes ? String(room.maxNotes) : "",
      (v) => {
        const s = v.trim();
        const n = Number(s);
        room.maxNotes = s !== "" && Number.isInteger(n) && n > 0 ? n : void 0;
      }
    );
    new import_obsidian.Setting(grid).setName(t.quiet).setDesc(t.quietDesc).addToggle(
      (box) => box.setValue(!!room.quiet).onChange((v) => {
        room.quiet = v;
        void this.saveAndRefresh();
      })
    );
    if (this.hasBacklogFile(room)) {
      new import_obsidian.Setting(grid).setName(t.backlogNote).setDesc(t.backlogNoteDesc);
    } else {
      new import_obsidian.Setting(grid).setName(t.pinBacklog).setDesc(t.pinBacklogDesc).addToggle(
        (box) => box.setValue(!!room.pinBacklog).onChange((v) => {
          room.pinBacklog = v;
          void this.saveAndRefresh();
        })
      );
    }
  }
  hasBacklogFile(room) {
    if (!room.folder)
      return false;
    const f = this.app.vault.getAbstractFileByPath(room.folder + "/BACKLOG.md");
    return f instanceof import_obsidian.TFile;
  }
  roomRole(room, t) {
    if (room.draft)
      return t.draftHint;
    if (room.parent)
      return t.roleNested + room.parent;
    if (room.folder)
      return t.roleHomeFolder;
    return t.roleGroup;
  }
  textField(parent, name, desc, value, assign) {
    new import_obsidian.Setting(parent).setName(name).setDesc(desc).addText(
      (box) => box.setValue(value).onChange((v) => {
        assign(v);
        this.debouncedSave();
      })
    );
  }
  fillHelp(pop, t) {
    pop.createDiv({ cls: "an-tou-help-kicker-line", text: t.helpTitle });
    const demo = pop.createDiv({ cls: "an-tou-help-demo" });
    const card = demo.createDiv({ cls: "an-tou-help-card" });
    card.createSpan({ cls: "an-tou-help-kicker", text: "Inbox" });
    card.createSpan({ cls: "an-tou-help-count", text: "3" });
    card.createEl("strong", { text: "\u5165\u53E3" });
    card.createSpan({ cls: "an-tou-help-line", text: "\u4ECA\u5929\u8FD9\u4E00\u5F20" });
    const keys = demo.createDiv({ cls: "an-tou-help-keys" });
    const addKey = (cls, cap, sample) => {
      const row = keys.createDiv({ cls: "an-tou-help-key" });
      row.createSpan({ cls: "an-tou-help-swatch " + cls });
      row.createSpan({ text: cap + " \xB7 " + sample });
    };
    addKey("is-kicker", t.helpKickerCap, "Inbox");
    addKey("is-name", t.helpNameCap, "\u5165\u53E3");
    addKey("is-line", t.helpLineCap, "\u4ECA\u5929\u8FD9\u4E00\u5F20");
    addKey("is-folder", t.helpFolderCap, "00-Inbox");
    addKey("is-count", t.helpCountCap, "3");
    pop.createDiv({ cls: "an-tou-help-note", text: t.helpFolderNote });
    const nest = pop.createDiv({ cls: "an-tou-help-nest" });
    nest.createDiv({ cls: "an-tou-help-kicker-line", text: t.helpParentCap });
    const home = nest.createDiv({ cls: "an-tou-help-flow" });
    home.createSpan({ cls: "an-tou-help-chip", text: t.helpHome });
    const cab = home.createDiv({ cls: "an-tou-help-mini" });
    cab.createSpan({ cls: "an-tou-help-kicker", text: "Cabinet" });
    cab.createEl("strong", { text: "\u6536\u7EB3\u67DC" });
    cab.createSpan({ cls: "an-tou-help-id", text: "cabinet" });
    home.createSpan({ cls: "an-tou-help-arrow", text: "\u2193" });
    home.createSpan({ cls: "an-tou-help-chip", text: t.helpInside });
    const child = home.createDiv({ cls: "an-tou-help-mini" });
    child.createSpan({ cls: "an-tou-help-kicker", text: "Thinking" });
    child.createEl("strong", { text: "\u4E2A\u4EBA\u601D\u8003" });
    child.createSpan({ cls: "an-tou-help-id", text: "cabinet" });
    nest.createDiv({ cls: "an-tou-help-note", text: t.helpParentNote });
    pop.createDiv({ cls: "an-tou-help-note", text: t.helpQuietNote });
  }
  async removeRoom(id) {
    this.plugin.settings.rooms = this.plugin.settings.rooms.filter((r) => r.id !== id);
    for (const room of this.plugin.settings.rooms) {
      if (room.parent === id)
        delete room.parent;
    }
    await this.saveAndRefresh();
    this.display();
  }
};
var AnTouPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    const saved = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, saved != null ? saved : {});
    if (!Array.isArray(this.settings.rooms))
      this.settings.rooms = [];
    if (!Array.isArray(this.settings.skipPaths))
      this.settings.skipPaths = [];
    if (this.settings.uiLang !== "en")
      this.settings.uiLang = "zh";
    if (!this.settings.title || this.settings.title === "An Tou") {
      this.settings.title = DEFAULT_TITLE;
    }
    if (this.settings.skipSeeded !== true) {
      if (!this.settings.skipPaths.includes("attachments")) {
        this.settings.skipPaths.push("attachments");
      }
      this.settings.skipSeeded = true;
      await this.saveSettings();
    }
    this.registerView(VIEW_TYPE, (leaf) => new DeskView(leaf, this));
    this.addCommand({
      id: "open-desk",
      name: "Open desk",
      callback: () => {
        void this.activateView();
      }
    });
    this.addSettingTab(new AnTouSettingTab(this.app, this));
    this.applyLook();
    this.app.workspace.onLayoutReady(async () => {
      if (this.settings.rooms.length === 0) {
        this.settings.rooms = this.scanRooms();
        await this.saveSettings();
      }
      if (this.settings.openOnStart)
        void this.activateView();
    });
  }
  onunload() {
    document.body.removeClass("an-tou-look");
  }
  applyLook() {
    document.body.toggleClass("an-tou-look", this.settings.applyLook !== false);
  }
  scanRooms() {
    const rooms = [];
    const used = /* @__PURE__ */ new Set();
    const skip = this.settings.skipPaths;
    const zh = this.settings.uiLang !== "en";
    const files = this.app.vault.getMarkdownFiles();
    const root = this.app.vault.getRoot();
    for (const child of root.children) {
      if (!(child instanceof import_obsidian.TFolder))
        continue;
      if (child.name.startsWith("."))
        continue;
      if (skipped(child.path, skip))
        continue;
      const id = uniqueId(slug(child.name), used);
      const n = this.mdCount(child.path, files);
      const room = {
        id,
        name: child.name,
        folder: child.path,
        kicker: kickerOf(child.name)
      };
      const line = noteCountLine(n, zh);
      if (line)
        room.line = line;
      rooms.push(room);
      for (const sub of child.children) {
        if (!(sub instanceof import_obsidian.TFolder))
          continue;
        if (sub.name.startsWith("."))
          continue;
        if (skipped(sub.path, skip))
          continue;
        const sid = uniqueId(slug(sub.name), used);
        const sn = this.mdCount(sub.path, files);
        const childRoom = {
          id: sid,
          name: sub.name,
          folder: sub.path,
          kicker: kickerOf(sub.name),
          parent: id
        };
        const childLine = noteCountLine(sn, zh);
        if (childLine)
          childRoom.line = childLine;
        rooms.push(childRoom);
      }
    }
    return rooms;
  }
  mdCount(folder, files) {
    const skip = this.settings.skipPaths;
    const all = files != null ? files : this.app.vault.getMarkdownFiles();
    return all.filter((f) => {
      if (!inFolder(f, folder))
        return false;
      if (skipped(f.path, skip))
        return false;
      return true;
    }).length;
  }
  mergeRooms(scanned) {
    const all = this.settings.rooms.slice();
    const usedIds = new Set(all.map((r) => r.id));
    const byFolder = /* @__PURE__ */ new Map();
    for (const room of all) {
      if (room.folder)
        byFolder.set(room.folder, room);
    }
    const idMap = /* @__PURE__ */ new Map();
    for (const s of scanned) {
      if (!s.folder)
        continue;
      const hit = byFolder.get(s.folder);
      if (hit)
        idMap.set(s.id, hit.id);
    }
    for (const s of scanned) {
      if (s.parent || !s.folder || idMap.has(s.id))
        continue;
      const prefix = s.folder + "/";
      const parents = /* @__PURE__ */ new Set();
      for (const room of all) {
        if (!room.folder || !room.folder.startsWith(prefix))
          continue;
        if (room.parent)
          parents.add(room.parent);
      }
      if (parents.size !== 1)
        continue;
      const pid = [...parents][0];
      idMap.set(s.id, pid);
      const parent = all.find((r) => r.id === pid);
      if (!parent)
        continue;
      if (!parent.folder)
        parent.folder = s.folder;
      if (isAutoKicker(parent))
        parent.kicker = s.kicker;
      if (isAutoLine(parent.line))
        parent.line = s.line;
    }
    for (const s of scanned) {
      const eid = idMap.get(s.id);
      if (!eid)
        continue;
      const ex = all.find((r) => r.id === eid);
      if (!ex)
        continue;
      if (isAutoKicker(ex))
        ex.kicker = s.kicker;
      if (isAutoLine(ex.line))
        ex.line = s.line;
    }
    for (const s of scanned) {
      if (idMap.has(s.id))
        continue;
      let parent = s.parent;
      if (parent) {
        const mapped = idMap.get(parent);
        if (mapped)
          parent = mapped;
      }
      const id = uniqueId(s.id, usedIds);
      idMap.set(s.id, id);
      const room = { ...s, id };
      if (parent)
        room.parent = parent;
      else
        delete room.parent;
      all.push(room);
      if (room.folder)
        byFolder.set(room.folder, room);
    }
    return all;
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  refreshDesks() {
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE)) {
      const view = leaf.view;
      if (view == null ? void 0 : view.render)
        void view.render();
    }
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE)[0];
    if (!leaf) {
      leaf = workspace.getLeaf("tab");
      await leaf.setViewState({ type: VIEW_TYPE, active: true });
    }
    await workspace.revealLeaf(leaf);
    if (this.settings.collapseExplorer && workspace.leftSplit) {
      workspace.leftSplit.collapse();
    }
  }
};
